export type Quadrant = "high-unpleasant" | "high-pleasant" | "low-unpleasant" | "low-pleasant";

export interface MoodWord {
  id: string;
  label: string;
  quadrant: Quadrant;
  intensity: number; // 1-5, 5 = most intense/central, drives bubble size
  description: string;
}

export const MOOD_DATA: MoodWord[] = [
  // HIGH ENERGY / UNPLEASANT (RED) - 25 words
  { id: "angry", label: "Angry", quadrant: "high-unpleasant", intensity: 5, description: "Feeling or showing strong annoyance, displeasure, or hostility." },
  { id: "frustrated", label: "Frustrated", quadrant: "high-unpleasant", intensity: 4, description: "Feeling distress and annoyance." },
  { id: "annoyed", label: "Annoyed", quadrant: "high-unpleasant", intensity: 3, description: "Slightly angry; irritated." },
  { id: "stressed", label: "Stressed", quadrant: "high-unpleasant", intensity: 4, description: "Experiencing mental or emotional strain." },
  { id: "anxious", label: "Anxious", quadrant: "high-unpleasant", intensity: 5, description: "Experiencing worry, unease, or nervousness." },
  { id: "worried", label: "Worried", quadrant: "high-unpleasant", intensity: 3, description: "Anxious or troubled about actual or potential problems." },
  { id: "overwhelmed", label: "Overwhelmed", quadrant: "high-unpleasant", intensity: 5, description: "Buried or drowning beneath a huge mass." },
  { id: "nervous", label: "Nervous", quadrant: "high-unpleasant", intensity: 4, description: "Easily agitated or alarmed; tending to be anxious." },
  { id: "jittery", label: "Jittery", quadrant: "high-unpleasant", intensity: 3, description: "Nervous or unable to relax." },
  { id: "restless", label: "Restless", quadrant: "high-unpleasant", intensity: 3, description: "Unable to rest or relax as a result of anxiety or boredom." },
  { id: "irritated", label: "Irritated", quadrant: "high-unpleasant", intensity: 4, description: "Showing or feeling slight anger; annoyed." },
  { id: "jealous", label: "Jealous", quadrant: "high-unpleasant", intensity: 3, description: "Feeling or showing envy of someone or their achievements and advantages." },
  { id: "envious", label: "Envious", quadrant: "high-unpleasant", intensity: 3, description: "Feeling or showing envy." },
  { id: "frightened", label: "Frightened", quadrant: "high-unpleasant", intensity: 5, description: "Afraid or anxious." },
  { id: "panicked", label: "Panicked", quadrant: "high-unpleasant", intensity: 5, description: "Feel or cause to feel panic." },
  { id: "shocked", label: "Shocked", quadrant: "high-unpleasant", intensity: 5, description: "Surprised and upset." },
  { id: "livid", label: "Livid", quadrant: "high-unpleasant", intensity: 5, description: "Furiously angry." },
  { id: "furious", label: "Furious", quadrant: "high-unpleasant", intensity: 5, description: "Extremely angry." },
  { id: "repulsed", label: "Repulsed", quadrant: "high-unpleasant", intensity: 4, description: "Cause (someone) to feel intense distaste and aversion." },
  { id: "troubled", label: "Troubled", quadrant: "high-unpleasant", intensity: 3, description: "Beset by problems or conflict." },
  { id: "enraged", label: "Enraged", quadrant: "high-unpleasant", intensity: 5, description: "Very angry; furious." },
  { id: "agitated", label: "Agitated", quadrant: "high-unpleasant", intensity: 4, description: "Feeling or appearing troubled or nervous." },
  { id: "hostile", label: "Hostile", quadrant: "high-unpleasant", intensity: 5, description: "Unfriendly; antagonistic." },
  { id: "outraged", label: "Outraged", quadrant: "high-unpleasant", intensity: 5, description: "Fierce anger, shock, or indignation." },
  { id: "terrified", label: "Terrified", quadrant: "high-unpleasant", intensity: 5, description: "Cause to feel extreme fear." },

  // HIGH ENERGY / PLEASANT (YELLOW/ORANGE) - 25 words
  { id: "excited", label: "Excited", quadrant: "high-pleasant", intensity: 5, description: "Very enthusiastic and eager." },
  { id: "energized", label: "Energized", quadrant: "high-pleasant", intensity: 5, description: "Given vitality and enthusiasm." },
  { id: "optimistic", label: "Optimistic", quadrant: "high-pleasant", intensity: 4, description: "Hopeful and confident about the future." },
  { id: "motivated", label: "Motivated", quadrant: "high-pleasant", intensity: 4, description: "Provided with a motive for doing something." },
  { id: "inspired", label: "Inspired", quadrant: "high-pleasant", intensity: 5, description: "Of extraordinary quality, as if arising from some external creative impulse." },
  { id: "confident", label: "Confident", quadrant: "high-pleasant", intensity: 4, description: "Feeling or showing confidence in oneself." },
  { id: "proud", label: "Proud", quadrant: "high-pleasant", intensity: 5, description: "Feeling deep pleasure or satisfaction as a result of one's own achievements." },
  { id: "amazed", label: "Amazed", quadrant: "high-pleasant", intensity: 5, description: "Greatly surprised; astonished." },
  { id: "hopeful", label: "Hopeful", quadrant: "high-pleasant", intensity: 3, description: "Feeling or inspiring optimism about a future event." },
  { id: "enthusiastic", label: "Enthusiastic", quadrant: "high-pleasant", intensity: 5, description: "Having or showing intense and eager enjoyment." },
  { id: "joyful", label: "Joyful", quadrant: "high-pleasant", intensity: 5, description: "Feeling, expressing, or causing great pleasure and happiness." },
  { id: "thrilled", label: "Thrilled", quadrant: "high-pleasant", intensity: 5, description: "Causing a feeling of sudden excitement." },
  { id: "elated", label: "Elated", quadrant: "high-pleasant", intensity: 5, description: "Ecstatically happy." },
  { id: "ecstatic", label: "Ecstatic", quadrant: "high-pleasant", intensity: 5, description: "Feeling or expressing overwhelming happiness." },
  { id: "surprised", label: "Surprised", quadrant: "high-pleasant", intensity: 4, description: "Feeling or showing surprise." },
  { id: "happy", label: "Happy", quadrant: "high-pleasant", intensity: 5, description: "Feeling or showing pleasure or contentment." },
  { id: "radiant", label: "Radiant", quadrant: "high-pleasant", intensity: 5, description: "Clearly emanating great joy, love, or health." },
  { id: "exhilarated", label: "Exhilarated", quadrant: "high-pleasant", intensity: 5, description: "Very happy, animated, or elated." },
  { id: "overjoyed", label: "Overjoyed", quadrant: "high-pleasant", intensity: 5, description: "Extremely happy." },
  { id: "gleeful", label: "Gleeful", quadrant: "high-pleasant", intensity: 4, description: "Exuberantly or triumphantly joyful." },
  { id: "playful", label: "Playful", quadrant: "high-pleasant", intensity: 4, description: "Fond of games and amusement; lighthearted." },
  { id: "vibrant", label: "Vibrant", quadrant: "high-pleasant", intensity: 5, description: "Full of energy and enthusiasm." },
  { id: "triumphant", label: "Triumphant", quadrant: "high-pleasant", intensity: 5, description: "Having won a battle or contest; victorious." },
  { id: "zestful", label: "Zestful", quadrant: "high-pleasant", intensity: 4, description: "Characterized by great enthusiasm and energy." },
  { id: "lively", label: "Lively", quadrant: "high-pleasant", intensity: 4, description: "Full of life and energy; active and outgoing." },

  // LOW ENERGY / PLEASANT (GREEN/TEAL) - 25 words
  { id: "calm", label: "Calm", quadrant: "low-pleasant", intensity: 5, description: "Not showing or feeling nervousness, anger, or other emotions." },
  { id: "at-ease", label: "At Ease", quadrant: "low-pleasant", intensity: 4, description: "Free from worry, awkwardness, or problems." },
  { id: "understood", label: "Understood", quadrant: "low-pleasant", intensity: 3, description: "Perceive the intended meaning of." },
  { id: "good", label: "Good", quadrant: "low-pleasant", intensity: 3, description: "To be desired or approved of." },
  { id: "thoughtful", label: "Thoughtful", quadrant: "low-pleasant", intensity: 3, description: "Absorbed in or involving thought." },
  { id: "appreciated", label: "Appreciated", quadrant: "low-pleasant", intensity: 4, description: "Recognize the full worth of." },
  { id: "relaxed", label: "Relaxed", quadrant: "low-pleasant", intensity: 5, description: "Free from tension and anxiety; at ease." },
  { id: "chill", label: "Chill", quadrant: "low-pleasant", intensity: 4, description: "Very relaxed or easygoing." },
  { id: "compassionate", label: "Compassionate", quadrant: "low-pleasant", intensity: 4, description: "Feeling or showing sympathy and concern for others." },
  { id: "sympathetic", label: "Sympathetic", quadrant: "low-pleasant", intensity: 5, description: "Feeling, showing, or expressing sympathy." },
  { id: "comfortable", label: "Comfortable", quadrant: "low-pleasant", intensity: 4, description: "Providing physical ease and relaxation." },
  { id: "peaceful", label: "Peaceful", quadrant: "low-pleasant", intensity: 5, description: "Free from disturbance; tranquil." },
  { id: "mellow", label: "Mellow", quadrant: "low-pleasant", intensity: 3, description: "Pleasantly smooth or soft; free from harshness." },
  { id: "balanced", label: "Balanced", quadrant: "low-pleasant", intensity: 4, description: "Keeping or showing a balance." },
  { id: "tranquil", label: "Tranquil", quadrant: "low-pleasant", intensity: 4, description: "Free from disturbance; calm." },
  { id: "carefree", label: "Carefree", quadrant: "low-pleasant", intensity: 4, description: "Free from anxiety or responsibility." },
  { id: "thankful", label: "Thankful", quadrant: "low-pleasant", intensity: 4, description: "Pleased and relieved." },
  { id: "empathetic", label: "Empathetic", quadrant: "low-pleasant", intensity: 4, description: "Showing an ability to understand and share the feelings of another." },
  { id: "content", label: "Content", quadrant: "low-pleasant", intensity: 5, description: "In a state of peaceful happiness." },
  { id: "serene", label: "Serene", quadrant: "low-pleasant", intensity: 5, description: "Calm, peaceful, and untroubled." },
  { id: "restful", label: "Restful", quadrant: "low-pleasant", intensity: 4, description: "Having a quiet and soothing quality." },
  { id: "cozy", label: "Cozy", quadrant: "low-pleasant", intensity: 4, description: "Giving a feeling of comfort, warmth, and relaxation." },
  { id: "satisfied", label: "Satisfied", quadrant: "low-pleasant", intensity: 4, description: "Contented; pleased with what one has." },
  { id: "centered", label: "Centered", quadrant: "low-pleasant", intensity: 4, description: "Emotionally stable and secure." },
  { id: "secure", label: "Secure", quadrant: "low-pleasant", intensity: 5, description: "Feeling no doubts about achieving; certain." },

  // LOW ENERGY / UNPLEASANT (BLUE) - 25 words
  { id: "down", label: "Down", quadrant: "low-unpleasant", intensity: 3, description: "Unhappy; depressed." },
  { id: "bored", label: "Bored", quadrant: "low-unpleasant", intensity: 2, description: "Feeling weary and restless through lack of interest." },
  { id: "meh", label: "Meh", quadrant: "low-unpleasant", intensity: 1, description: "Expressing a lack of interest or enthusiasm." },
  { id: "tired", label: "Tired", quadrant: "low-unpleasant", intensity: 3, description: "In need of sleep or rest." },
  { id: "fatigued", label: "Fatigued", quadrant: "low-unpleasant", intensity: 4, description: "Cause to feel tired or exhausted." },
  { id: "disengaged", label: "Disengaged", quadrant: "low-unpleasant", intensity: 3, description: "Emotionally detached." },
  { id: "apathetic", label: "Apathetic", quadrant: "low-unpleasant", intensity: 4, description: "Showing or feeling no interest, enthusiasm, or concern." },
  { id: "sad", label: "Sad", quadrant: "low-unpleasant", intensity: 5, description: "Feeling or showing sorrow; unhappy." },
  { id: "lonely", label: "Lonely", quadrant: "low-unpleasant", intensity: 5, description: "Sad because one has no friends or company." },
  { id: "discouraged", label: "Discouraged", quadrant: "low-unpleasant", intensity: 4, description: "Having lost confidence or enthusiasm." },
  { id: "exhausted", label: "Exhausted", quadrant: "low-unpleasant", intensity: 5, description: "Drained of one's physical or mental resources." },
  { id: "helpless", label: "Helpless", quadrant: "low-unpleasant", intensity: 5, description: "Unable to defend oneself or to act without help." },
  { id: "despairing", label: "Despairing", quadrant: "low-unpleasant", intensity: 5, description: "Showing the loss of all hope." },
  { id: "hopeless", label: "Hopeless", quadrant: "low-unpleasant", intensity: 5, description: "Feeling or causing despair about something." },
  { id: "depressed", label: "Depressed", quadrant: "low-unpleasant", intensity: 5, description: "In a state of general unhappiness or despondency." },
  { id: "alienated", label: "Alienated", quadrant: "low-unpleasant", intensity: 4, description: "Experiencing or inducing feelings of isolation." },
  { id: "miserable", label: "Miserable", quadrant: "low-unpleasant", intensity: 5, description: "Wretchedly unhappy or uncomfortable." },
  { id: "pessimistic", label: "Pessimistic", quadrant: "low-unpleasant", intensity: 3, description: "Tending to see the worst aspect of things." },
  { id: "morose", label: "Morose", quadrant: "low-unpleasant", intensity: 4, description: "Sullen and ill-tempered." },
  { id: "gloomy", label: "Gloomy", quadrant: "low-unpleasant", intensity: 3, description: "Dark or poorly lit, especially so as to appear depressing." },
  { id: "disappointed", label: "Disappointed", quadrant: "low-unpleasant", intensity: 3, description: "Sad or displeased because someone or something has failed to fulfill one's hopes." },
  { id: "melancholy", label: "Melancholy", quadrant: "low-unpleasant", intensity: 4, description: "A feeling of pensive sadness, typically with no obvious cause." },
  { id: "despondent", label: "Despondent", quadrant: "low-unpleasant", intensity: 5, description: "In low spirits from loss of hope or courage." },
  { id: "drained", label: "Drained", quadrant: "low-unpleasant", intensity: 4, description: "Deprived of strength or vitality." },
  { id: "numb", label: "Numb", quadrant: "low-unpleasant", intensity: 5, description: "Deprived of the power of sensation." }
];
