// Generated by Framer (7e6a191)
import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import {
  addFonts,
  addPropertyControls,
  ComponentViewportProvider,
  ControlType,
  cx,
  forwardLoader,
  getFonts,
  getFontsFromSharedStyle,
  getLoadingLazyAtYPosition,
  Image as Image1,
  Link,
  RichText,
  runTasksWithYield,
  SmartComponentScopedContainer,
  SVG,
  useComponentViewport,
  useLocaleInfo,
  useVariantState,
  withCSS,
} from "framer";
import { LayoutGroup, motion, MotionConfigContext } from "framer-motion";
import * as React from "react";
import { useRef } from "react";
import YoutubeLogo from "https://framerusercontent.com/modules/4XTgiZQu54CjbB5dhliq/4qeXVdBQKTlCfMoVGgCT/rR4Yw6OW8.js";
import TwitterLogo from "https://framerusercontent.com/modules/c4HsHmhw2A874wd4HUv4/eiMgKnTLbWkmDtuRAl8s/Nz7HVaCWU.js";
import RedditLogo from "https://framerusercontent.com/modules/oHasmoNHg6ZpS9RAigLE/UAAxFnKFr7C5NJ1tiM86/F5lUenUzP.js";
import InstagramLogo from "https://framerusercontent.com/modules/PtxaBiSAA5V6LvrpAt6G/EsR1AqByikNQR8Cp2V8c/UD0eTfbk_.js";
import FacebookLogo from "https://framerusercontent.com/modules/Y0c19ostjQ6JrIrS9EpB/H6GkscheXEvK1c9LQrFc/QDC8_m4BS.js";
import * as sharedStyle2 from "https://framerusercontent.com/modules/7XYEa2RFVsgTlGtXyQ2F/LfkwqQG8H0R81MLYcvCI/A9EvreP5V.js";
import * as sharedStyle from "https://framerusercontent.com/modules/eYvUmCkMnKOkznnVuQud/0jfH9IdICtj5k7ju2DUM/D__wC9hxO.js";
import * as sharedStyle1 from "https://framerusercontent.com/modules/S8Cu2wm7ZILuKL7hmdnD/XGacJEhnYUPggwKn5fjb/EEduRU57x.js";
import * as sharedStyle3 from "https://framerusercontent.com/modules/PyC4Ov0A3nkq40HiSn6I/ZiiqgfU38CYwok9qkxWt/Kz9GWIUzc.js";
import DownloadButton from "https://framerusercontent.com/modules/1A6yp1k7iDdOH1OS5ko5/HZ0dfuwqLBjegQpueUET/B8aAPWvMX.js";
const DownloadButtonFonts = getFonts(DownloadButton);
const InstagramLogoFonts = getFonts(InstagramLogo);
const FacebookLogoFonts = getFonts(FacebookLogo);
const RedditLogoFonts = getFonts(RedditLogo);
const TwitterLogoFonts = getFonts(TwitterLogo);
const YoutubeLogoFonts = getFonts(YoutubeLogo);
const cycleOrder = ["nDxwOaqqO", "TrOL0ndGc", "D35XkzQGc"];
const serializationHash = "framer-CRn1M";
const variantClassNames = {
  D35XkzQGc: "framer-v-tqwtez",
  nDxwOaqqO: "framer-v-45gk8g",
  TrOL0ndGc: "framer-v-vu3yea",
};
function addPropertyOverrides(overrides, ...variants) {
  const nextOverrides = {};
  variants?.forEach(
    (variant) => variant && Object.assign(nextOverrides, overrides[variant])
  );
  return nextOverrides;
}
const p5B5KxpAb = undefined;
const transition1 = { bounce: 0.2, delay: 0, duration: 0.4, type: "spring" };
const matchVariant = (...args) => {
  for (const arg of args) {
    if (arg && typeof arg === "string") return arg;
  }
  return undefined;
};
const transition2 = { bounce: 0.25, delay: 0, duration: 0.45, type: "spring" };
const animation = {
  opacity: 0.5,
  rotate: 0,
  rotateX: 0,
  rotateY: 0,
  scale: 1,
  skewX: 0,
  skewY: 0,
  transition: transition2,
};
const Transition = ({ value, children }) => {
  const config = React.useContext(MotionConfigContext);
  const transition = value ?? config.transition;
  const contextValue = React.useMemo(
    () => ({ ...config, transition }),
    [JSON.stringify(transition)]
  );
  return /*#__PURE__*/ _jsx(MotionConfigContext.Provider, {
    value: contextValue,
    children: children,
  });
};
const humanReadableVariantMap = {
  Desktop: "nDxwOaqqO",
  Phone: "D35XkzQGc",
  Tablet: "TrOL0ndGc",
};
const Variants = motion.create(React.Fragment);
const getProps = ({ cTA, height, id, width, ...props }) => {
  return {
    ...props,
    p5B5KxpAb: cTA ?? props.p5B5KxpAb ?? true,
    variant:
      humanReadableVariantMap[props.variant] ?? props.variant ?? "nDxwOaqqO",
  };
};
const createLayoutDependency = (props, variants) => {
  if (props.layoutDependency)
    return variants.join("-") + props.layoutDependency;
  return variants.join("-");
};
const Component = /*#__PURE__*/ React.forwardRef(function (props, ref) {
  const fallbackRef = useRef(null);
  const refBinding = ref ?? fallbackRef;
  const defaultLayoutId = React.useId();
  const { activeLocale, setLocale } = useLocaleInfo();
  const componentViewport = useComponentViewport();
  const { style, className, layoutId, variant, p5B5KxpAb, ...restProps } =
    getProps(props);
  const {
    baseVariant,
    classNames,
    clearLoadingGesture,
    gestureHandlers,
    gestureVariant,
    isLoading,
    setGestureState,
    setVariant,
    variants,
  } = useVariantState({
    cycleOrder,
    defaultVariant: "nDxwOaqqO",
    ref: refBinding,
    variant,
    variantClassNames,
  });
  const layoutDependency = createLayoutDependency(props, variants);
  const sharedStyleClassNames = [
    sharedStyle.className,
    sharedStyle1.className,
    sharedStyle2.className,
    sharedStyle3.className,
  ];
  const scopingClassNames = cx(serializationHash, ...sharedStyleClassNames);
  return /*#__PURE__*/ _jsx(LayoutGroup, {
    id: layoutId ?? defaultLayoutId,
    children: /*#__PURE__*/ _jsx(Variants, {
      animate: variants,
      initial: false,
      children: /*#__PURE__*/ _jsx(Transition, {
        value: transition1,
        children: /*#__PURE__*/ _jsxs(motion.div, {
          ...restProps,
          ...gestureHandlers,
          className: cx(
            scopingClassNames,
            "framer-45gk8g",
            className,
            classNames
          ),
          "data-framer-name": "Desktop",
          layoutDependency: layoutDependency,
          layoutId: "nDxwOaqqO",
          ref: refBinding,
          style: { ...style },
          ...addPropertyOverrides(
            {
              D35XkzQGc: { "data-framer-name": "Phone" },
              TrOL0ndGc: { "data-framer-name": "Tablet" },
            },
            baseVariant,
            gestureVariant
          ),
          children: [
            p5B5KxpAb !== false &&
              /*#__PURE__*/ _jsx(motion.div, {
                className: "framer-kc03lq",
                layoutDependency: layoutDependency,
                layoutId: "qsOCsB9UZ",
                children: /*#__PURE__*/ _jsxs(Image1, {
                  background: {
                    alt: "",
                    fit: "fill",
                    loading: getLoadingLazyAtYPosition(
                      (componentViewport?.y || 0) +
                        0 +
                        (((componentViewport?.height || 200) - 0 - 523.8) / 2 +
                          0 +
                          0) +
                        0 +
                        0
                    ),
                    pixelHeight: 2160,
                    pixelWidth: 3841,
                    sizes: "1000px",
                    src: "https://framerusercontent.com/images/55Eyxb29Rl5W43Clnfu4Y8OlRNw.png?scale-down-to=1024&width=3841&height=2160",
                  },
                  className: "framer-19bt5g6",
                  "data-border": true,
                  "data-framer-name": "Top",
                  layoutDependency: layoutDependency,
                  layoutId: "OfTB85WqP",
                  style: {
                    "--border-bottom-width": "1px",
                    "--border-color":
                      "var(--token-0ecaa262-9aac-4113-a5a5-5bfcb0d17214, rgb(53, 48, 43))",
                    "--border-left-width": "1px",
                    "--border-right-width": "1px",
                    "--border-style": "solid",
                    "--border-top-width": "1px",
                    borderBottomLeftRadius: 24,
                    borderBottomRightRadius: 24,
                    borderTopLeftRadius: 24,
                    borderTopRightRadius: 24,
                  },
                  variants: {
                    D35XkzQGc: {
                      borderBottomLeftRadius: 16,
                      borderBottomRightRadius: 16,
                      borderTopLeftRadius: 16,
                      borderTopRightRadius: 16,
                    },
                    TrOL0ndGc: {
                      borderBottomLeftRadius: 16,
                      borderBottomRightRadius: 16,
                      borderTopLeftRadius: 16,
                      borderTopRightRadius: 16,
                    },
                  },
                  ...addPropertyOverrides(
                    {
                      D35XkzQGc: {
                        background: {
                          alt: "",
                          fit: "fill",
                          loading: getLoadingLazyAtYPosition(
                            (componentViewport?.y || 0) +
                              0 +
                              (((componentViewport?.height || 200) -
                                0 -
                                695.8) /
                                2 +
                                0 +
                                0) +
                              0 +
                              0
                          ),
                          pixelHeight: 2160,
                          pixelWidth: 3841,
                          sizes: `calc(${
                            componentViewport?.width || "100vw"
                          } - 32px)`,
                          src: "https://framerusercontent.com/images/55Eyxb29Rl5W43Clnfu4Y8OlRNw.png?scale-down-to=1024&width=3841&height=2160",
                        },
                      },
                      TrOL0ndGc: {
                        background: {
                          alt: "",
                          fit: "fill",
                          loading: getLoadingLazyAtYPosition(
                            (componentViewport?.y || 0) +
                              0 +
                              (((componentViewport?.height || 200) -
                                0 -
                                523.8) /
                                2 +
                                0 +
                                0) +
                              0
                          ),
                          pixelHeight: 2160,
                          pixelWidth: 3841,
                          sizes: `max(${
                            componentViewport?.width || "100vw"
                          } - 32px, 1px)`,
                          src: "https://framerusercontent.com/images/55Eyxb29Rl5W43Clnfu4Y8OlRNw.png?scale-down-to=1024&width=3841&height=2160",
                        },
                      },
                    },
                    baseVariant,
                    gestureVariant
                  ),
                  children: [
                    /*#__PURE__*/ _jsxs(motion.div, {
                      className: "framer-1o0x3a7",
                      layoutDependency: layoutDependency,
                      layoutId: "P7hBKbJG9",
                      children: [
                        /*#__PURE__*/ _jsx(RichText, {
                          __fromCanvasComponent: true,
                          children: /*#__PURE__*/ _jsx(React.Fragment, {
                            children: /*#__PURE__*/ _jsx(motion.h1, {
                              className: "framer-styles-preset-snfl5q",
                              "data-styles-preset": "D__wC9hxO",
                              style: {
                                "--framer-text-color":
                                  "var(--extracted-gdpscs, var(--token-6c0aaddc-46bb-4a8c-a780-8357980b9d48, rgb(241, 230, 219)))",
                              },
                              children: "Begin your journey",
                            }),
                          }),
                          className: "framer-1rd366y",
                          fonts: ["Inter"],
                          layoutDependency: layoutDependency,
                          layoutId: "Gry6ZAj3w",
                          style: {
                            "--extracted-gdpscs":
                              "var(--token-6c0aaddc-46bb-4a8c-a780-8357980b9d48, rgb(241, 230, 219))",
                            "--framer-link-text-color": "rgb(0, 153, 255)",
                            "--framer-link-text-decoration": "underline",
                          },
                          verticalAlignment: "top",
                          withExternalLayout: true,
                        }),
                        /*#__PURE__*/ _jsx(RichText, {
                          __fromCanvasComponent: true,
                          children: /*#__PURE__*/ _jsx(React.Fragment, {
                            children: /*#__PURE__*/ _jsx(motion.p, {
                              className: "framer-styles-preset-10oprdx",
                              "data-styles-preset": "EEduRU57x",
                              style: {
                                "--framer-text-alignment": "center",
                                "--framer-text-color":
                                  "var(--extracted-r6o4lv, var(--token-6c0aaddc-46bb-4a8c-a780-8357980b9d48, rgb(241, 230, 219)))",
                              },
                              children: "Take the first step today",
                            }),
                          }),
                          className: "framer-7v9337",
                          fonts: ["Inter"],
                          layoutDependency: layoutDependency,
                          layoutId: "QtYbpTo6p",
                          style: {
                            "--extracted-r6o4lv":
                              "var(--token-6c0aaddc-46bb-4a8c-a780-8357980b9d48, rgb(241, 230, 219))",
                            "--framer-link-text-color": "rgb(0, 153, 255)",
                            "--framer-link-text-decoration": "underline",
                          },
                          verticalAlignment: "top",
                          withExternalLayout: true,
                        }),
                      ],
                    }),
                    /*#__PURE__*/ _jsx(ComponentViewportProvider, {
                      height: 48,
                      width: "144px",
                      y:
                        (componentViewport?.y || 0) +
                        0 +
                        (((componentViewport?.height || 200) - 0 - 523.8) / 2 +
                          0 +
                          0) +
                        0 +
                        0 +
                        128 +
                        305.6,
                      ...addPropertyOverrides(
                        {
                          D35XkzQGc: {
                            y:
                              (componentViewport?.y || 0) +
                              0 +
                              (((componentViewport?.height || 200) -
                                0 -
                                695.8) /
                                2 +
                                0 +
                                0) +
                              0 +
                              0 +
                              128 +
                              305.6,
                          },
                          TrOL0ndGc: {
                            y:
                              (componentViewport?.y || 0) +
                              0 +
                              (((componentViewport?.height || 200) -
                                0 -
                                523.8) /
                                2 +
                                0 +
                                0) +
                              0 +
                              128 +
                              305.6,
                          },
                        },
                        baseVariant,
                        gestureVariant
                      ),
                      children: /*#__PURE__*/ _jsx(
                        SmartComponentScopedContainer,
                        {
                          className: "framer-lr6ox5-container",
                          layoutDependency: layoutDependency,
                          layoutId: "p_oJt5lwD-container",
                          nodeId: "p_oJt5lwD",
                          rendersWithMotion: true,
                          scopeId: "O6t7eSwWb",
                          children: /*#__PURE__*/ _jsx(DownloadButton, {
                            etyq7tFCs: "/dashboard",
                            height: "100%",
                            id: "p_oJt5lwD",
                            layoutId: "p_oJt5lwD",
                            style: { height: "100%", width: "100%" },
                            variant: matchVariant("ftbVpeA1b"),
                            width: "100%",
                            XDhrjNHnD: "Get Started",
                          }),
                        }
                      ),
                    }),
                  ],
                }),
              }),
            /*#__PURE__*/ _jsx(motion.div, {
              className: "framer-1s3h76o",
              "data-framer-name": "Bottom",
              layoutDependency: layoutDependency,
              layoutId: "jJFh0NIBT",
              style: {
                backgroundColor:
                  "var(--token-46c57772-6ea6-44fd-970d-ca4fb7a65057, rgb(229, 216, 202))",
              },
              children: /*#__PURE__*/ _jsxs(motion.div, {
                className: "framer-1g7ar5k",
                layoutDependency: layoutDependency,
                layoutId: "G2aWOVc4k",
                children: [
                  /*#__PURE__*/ _jsxs(motion.div, {
                    className: "framer-17w9zn4",
                    layoutDependency: layoutDependency,
                    layoutId: "ygfEUnmAM",
                    children: [
                      /*#__PURE__*/ _jsxs(motion.div, {
                        className: "framer-12tdyuf",
                        "data-framer-name": "Socials",
                        layoutDependency: layoutDependency,
                        layoutId: "q2ce9SKMA",
                        children: [
                          /*#__PURE__*/ _jsxs(SVG, {
                            className: "framer-1i1fe27",
                            layoutDependency: layoutDependency,
                            layoutId: "OWtfkqRet",
                            requiresOverflowVisible: false,
                            svg: '<svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" viewBox="0 0 51.527 24.016" overflow="visible"><path d="M 0 23.416 C 1.051 22.755 1.922 21.794 2.582 19.963 L 8.856 2.822 C 9.126 2.042 9.126 1.382 8.916 0.781 L 12.849 0.781 L 20.114 20.114 C 20.713 21.734 21.344 22.755 22.365 23.386 L 22.365 23.505 L 15.22 23.505 L 15.22 23.416 C 16.421 22.755 16.51 21.764 15.94 20.144 L 14.739 16.662 L 6.034 16.662 L 4.863 20.053 C 4.263 21.855 4.323 22.785 5.374 23.416 L 5.374 23.505 L 0 23.505 Z M 6.635 14.98 L 14.169 14.98 L 10.418 4.054 L 6.634 14.98 Z M 28.503 24.016 C 24.3 24.016 21.569 21.974 21.148 18.643 L 24.36 18.643 C 24.631 21.044 26.012 22.485 28.533 22.485 C 30.274 22.485 31.535 21.764 31.535 20.384 C 31.535 18.853 30.274 18.373 27.212 17.261 C 24.391 16.241 21.929 15.22 21.929 12.459 C 21.929 9.847 24.391 8.256 27.903 8.256 C 31.595 8.256 33.996 9.937 34.567 12.759 L 31.415 12.759 C 31.175 10.988 30.034 9.787 27.812 9.787 C 26.162 9.787 25.111 10.477 25.111 11.678 C 25.111 13.209 26.612 13.839 29.374 14.8 C 32.585 15.911 34.747 16.991 34.747 19.633 C 34.747 22.575 32.015 24.016 28.503 24.016 Z M 35.077 23.505 L 35.077 23.386 C 36.156 22.635 36.337 21.524 36.337 19.333 L 36.337 4.233 C 36.337 2.432 36.126 1.411 35.226 0.661 L 35.226 0.57 L 40.059 0 L 40.089 0.12 C 39.939 1.02 39.879 1.801 39.879 4.233 L 39.879 12.068 C 40.81 9.936 42.731 8.255 45.553 8.255 C 48.495 8.255 50.355 9.876 50.355 13.988 L 50.355 19.333 C 50.355 21.524 50.506 22.634 51.527 23.384 L 51.527 23.505 L 45.702 23.505 L 45.702 23.385 C 46.632 22.634 46.783 21.524 46.783 19.333 L 46.783 14.11 C 46.783 11.467 45.822 10.357 43.931 10.357 C 41.799 10.357 40.359 12.008 39.878 14.049 L 39.878 19.333 C 39.878 21.524 40.058 22.634 41.109 23.384 L 41.109 23.505 L 35.075 23.505 Z" fill="rgba(53, 48, 44, 0.5)"></path></svg>',
                            withExternalLayout: true,
                            children: [
                              /*#__PURE__*/ _jsx(SVG, {
                                className: "framer-e7r9t9",
                                layoutDependency: layoutDependency,
                                layoutId: "ICwGP3xii",
                                requiresOverflowVisible: false,
                                svg: '<svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" viewBox="0 0 22.365 22.724" overflow="visible"><path d="M 0 22.635 C 1.051 21.974 1.922 21.013 2.582 19.182 L 8.856 2.041 C 9.126 1.261 9.126 0.601 8.916 0 L 12.849 0 L 20.114 19.333 C 20.713 20.953 21.344 21.974 22.365 22.605 L 22.365 22.724 L 15.22 22.724 L 15.22 22.635 C 16.421 21.974 16.51 20.983 15.94 19.363 L 14.739 15.881 L 6.034 15.881 L 4.863 19.272 C 4.263 21.074 4.323 22.004 5.374 22.635 L 5.374 22.724 L 0 22.724 Z" fill="transparent"></path></svg>',
                                withExternalLayout: true,
                              }),
                              /*#__PURE__*/ _jsx(SVG, {
                                className: "framer-iuk3s1",
                                layoutDependency: layoutDependency,
                                layoutId: "LRZ18KM_n",
                                requiresOverflowVisible: false,
                                svg: '<svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" viewBox="0 0 7.535 10.926" overflow="visible"><path d="M 0.001 10.926 L 7.535 10.926 L 3.784 0 L 0 10.926 Z" fill="transparent"></path></svg>',
                                withExternalLayout: true,
                              }),
                              /*#__PURE__*/ _jsx(SVG, {
                                className: "framer-1cv9025",
                                layoutDependency: layoutDependency,
                                layoutId: "uLsmSiDnQ",
                                requiresOverflowVisible: false,
                                svg: '<svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" viewBox="0 0 13.599 15.76" overflow="visible"><path d="M 7.355 15.76 C 3.152 15.76 0.421 13.718 0 10.387 L 3.212 10.387 C 3.482 12.788 4.863 14.229 7.385 14.229 C 9.126 14.229 10.387 13.508 10.387 12.128 C 10.387 10.597 9.126 10.117 6.063 9.005 C 3.242 7.985 0.78 6.964 0.78 4.203 C 0.78 1.591 3.242 0 6.754 0 C 10.447 0 12.848 1.681 13.419 4.503 L 10.266 4.503 C 10.026 2.732 8.886 1.531 6.664 1.531 C 5.013 1.531 3.963 2.221 3.963 3.422 C 3.963 4.953 5.463 5.583 8.226 6.544 C 11.437 7.655 13.599 8.735 13.599 11.377 C 13.599 14.319 10.867 15.76 7.355 15.76 Z" fill="transparent"></path></svg>',
                                withExternalLayout: true,
                              }),
                              /*#__PURE__*/ _jsx(SVG, {
                                className: "framer-13kmlwq",
                                layoutDependency: layoutDependency,
                                layoutId: "NSsbg33gm",
                                requiresOverflowVisible: false,
                                svg: '<svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" viewBox="0 0 16.452 23.505" overflow="visible"><path d="M 0.002 23.505 L 0.002 23.386 C 1.081 22.635 1.262 21.524 1.262 19.333 L 1.262 4.233 C 1.262 2.432 1.051 1.411 0.151 0.661 L 0.151 0.57 L 4.984 0 L 5.014 0.12 C 4.864 1.02 4.804 1.801 4.804 4.233 L 4.804 12.068 C 5.735 9.936 7.656 8.255 10.478 8.255 C 13.42 8.255 15.28 9.876 15.28 13.988 L 15.28 19.333 C 15.28 21.524 15.431 22.634 16.452 23.384 L 16.452 23.505 L 10.627 23.505 L 10.627 23.385 C 11.557 22.634 11.708 21.524 11.708 19.333 L 11.708 14.11 C 11.708 11.467 10.747 10.357 8.856 10.357 C 6.724 10.357 5.284 12.008 4.803 14.049 L 4.803 19.333 C 4.803 21.524 4.983 22.634 6.034 23.384 L 6.034 23.505 L 0 23.505 Z" fill="transparent"></path></svg>',
                                withExternalLayout: true,
                              }),
                            ],
                          }),
                          /*#__PURE__*/ _jsxs(motion.div, {
                            className: "framer-jablm",
                            layoutDependency: layoutDependency,
                            layoutId: "J5FrFLL9t",
                            style: { opacity: 0.5 },
                            children: [
                              /*#__PURE__*/ _jsx(Link, {
                                href: "https://www.instagram.com/talktoash.official/",
                                motionChild: true,
                                nodeId: "XONwbliiZ",
                                openInNewTab: true,
                                scopeId: "O6t7eSwWb",
                                children: /*#__PURE__*/ _jsx(motion.a, {
                                  className: "framer-1j2a3xy framer-nyt7b7",
                                  layoutDependency: layoutDependency,
                                  layoutId: "XONwbliiZ",
                                  children: /*#__PURE__*/ _jsx(InstagramLogo, {
                                    animated: true,
                                    className: "framer-y2r9di",
                                    layoutDependency: layoutDependency,
                                    layoutId: "S0jZRGOj7",
                                    style: {
                                      "--1m6trwb": 0,
                                      "--21h8s6":
                                        "var(--token-0ecaa262-9aac-4113-a5a5-5bfcb0d17214, rgb(53, 48, 43))",
                                      "--pgex8v": 1.5,
                                    },
                                    whileHover: animation,
                                  }),
                                }),
                              }),
                              /*#__PURE__*/ _jsx(Link, {
                                href: "http://facebook.com/talktoashai",
                                motionChild: true,
                                nodeId: "j3Ff2iHl8",
                                openInNewTab: true,
                                scopeId: "O6t7eSwWb",
                                children: /*#__PURE__*/ _jsx(motion.a, {
                                  className: "framer-1xrq5wx framer-nyt7b7",
                                  layoutDependency: layoutDependency,
                                  layoutId: "j3Ff2iHl8",
                                  children: /*#__PURE__*/ _jsx(FacebookLogo, {
                                    animated: true,
                                    className: "framer-1mlkvu4",
                                    layoutDependency: layoutDependency,
                                    layoutId: "CS0AB8oM7",
                                    style: {
                                      "--1m6trwb": 0,
                                      "--21h8s6":
                                        "var(--token-0ecaa262-9aac-4113-a5a5-5bfcb0d17214, rgb(53, 48, 43))",
                                      "--pgex8v": 1.5,
                                    },
                                    whileHover: animation,
                                  }),
                                }),
                              }),
                              /*#__PURE__*/ _jsx(Link, {
                                href: "https://www.reddit.com/r/ashai/",
                                motionChild: true,
                                nodeId: "MAyg1EBT4",
                                openInNewTab: true,
                                scopeId: "O6t7eSwWb",
                                children: /*#__PURE__*/ _jsx(motion.a, {
                                  className: "framer-mnnosz framer-nyt7b7",
                                  layoutDependency: layoutDependency,
                                  layoutId: "MAyg1EBT4",
                                  children: /*#__PURE__*/ _jsx(RedditLogo, {
                                    animated: true,
                                    className: "framer-34edvh",
                                    layoutDependency: layoutDependency,
                                    layoutId: "IrkW4GujO",
                                    style: {
                                      "--1m6trwb": 0,
                                      "--21h8s6":
                                        "var(--token-0ecaa262-9aac-4113-a5a5-5bfcb0d17214, rgb(53, 48, 43))",
                                      "--pgex8v": 1.5,
                                    },
                                    whileHover: animation,
                                  }),
                                }),
                              }),
                              /*#__PURE__*/ _jsx(Link, {
                                href: "http://x.com/talktoashAI",
                                motionChild: true,
                                nodeId: "thCz3J16h",
                                openInNewTab: true,
                                scopeId: "O6t7eSwWb",
                                children: /*#__PURE__*/ _jsx(motion.a, {
                                  className: "framer-hwzf0h framer-nyt7b7",
                                  layoutDependency: layoutDependency,
                                  layoutId: "thCz3J16h",
                                  children: /*#__PURE__*/ _jsx(TwitterLogo, {
                                    animated: true,
                                    className: "framer-3r19sq",
                                    layoutDependency: layoutDependency,
                                    layoutId: "rWy7e74N2",
                                    style: {
                                      "--1m6trwb": 0,
                                      "--21h8s6":
                                        "var(--token-0ecaa262-9aac-4113-a5a5-5bfcb0d17214, rgb(53, 48, 43))",
                                      "--pgex8v": 1.5,
                                    },
                                    whileHover: animation,
                                  }),
                                }),
                              }),
                              /*#__PURE__*/ _jsx(Link, {
                                href: "https://www.youtube.com/@ashaimentalhealth",
                                motionChild: true,
                                nodeId: "erLQds9a1",
                                openInNewTab: true,
                                scopeId: "O6t7eSwWb",
                                children: /*#__PURE__*/ _jsx(motion.a, {
                                  className: "framer-v8rjm3 framer-nyt7b7",
                                  layoutDependency: layoutDependency,
                                  layoutId: "erLQds9a1",
                                  children: /*#__PURE__*/ _jsx(YoutubeLogo, {
                                    animated: true,
                                    className: "framer-1vs7hie",
                                    layoutDependency: layoutDependency,
                                    layoutId: "QLf71ZTx0",
                                    style: {
                                      "--1m6trwb": 0,
                                      "--21h8s6":
                                        "var(--token-0ecaa262-9aac-4113-a5a5-5bfcb0d17214, rgb(53, 48, 43))",
                                      "--pgex8v": 1.5,
                                    },
                                    whileHover: animation,
                                  }),
                                }),
                              }),
                            ],
                          }),
                        ],
                      }),
                      /*#__PURE__*/ _jsx(motion.div, {
                        className: "framer-6egu0i",
                        "data-framer-name": "Resources",
                        layoutDependency: layoutDependency,
                        layoutId: "Ojxg9SCQr",
                        children: /*#__PURE__*/ _jsxs(motion.div, {
                          className: "framer-1mlrs5y",
                          layoutDependency: layoutDependency,
                          layoutId: "JSjzN1Y3H",
                          children: [
                            /*#__PURE__*/ _jsx(RichText, {
                              __fromCanvasComponent: true,
                              children: /*#__PURE__*/ _jsx(React.Fragment, {
                                children: /*#__PURE__*/ _jsx(motion.p, {
                                  style: {
                                    "--font-selector": "R0Y7RE0gU2Fucy02MDA=",
                                    "--framer-font-family":
                                      '"DM Sans", "DM Sans Placeholder", sans-serif',
                                    "--framer-font-size": "12px",
                                    "--framer-font-weight": "600",
                                    "--framer-letter-spacing": "0.1em",
                                    "--framer-line-height": "130%",
                                    "--framer-text-color":
                                      "var(--extracted-r6o4lv, var(--token-0ecaa262-9aac-4113-a5a5-5bfcb0d17214, rgb(53, 48, 43)))",
                                  },
                                  children: "GET IN TOUCH",
                                }),
                              }),
                              className: "framer-22165p",
                              fonts: ["GF;DM Sans-600"],
                              layoutDependency: layoutDependency,
                              layoutId: "Bdbs6Jfkd",
                              style: {
                                "--extracted-r6o4lv":
                                  "var(--token-0ecaa262-9aac-4113-a5a5-5bfcb0d17214, rgb(53, 48, 43))",
                                "--framer-link-text-color": "rgb(0, 153, 255)",
                                "--framer-link-text-decoration": "underline",
                              },
                              verticalAlignment: "top",
                              withExternalLayout: true,
                            }),
                            /*#__PURE__*/ _jsx(motion.div, {
                              className: "framer-1og3o1n",
                              layoutDependency: layoutDependency,
                              layoutId: "cwD88iigJ",
                              children: /*#__PURE__*/ _jsxs(motion.div, {
                                className: "framer-zw0w8w",
                                layoutDependency: layoutDependency,
                                layoutId: "KPsY0qpVg",
                                children: [
                                  /*#__PURE__*/ _jsx(RichText, {
                                    __fromCanvasComponent: true,
                                    children: /*#__PURE__*/ _jsx(
                                      React.Fragment,
                                      {
                                        children: /*#__PURE__*/ _jsx(motion.p, {
                                          style: {
                                            "--font-selector":
                                              "R0Y7RE0gU2Fucy01MDA=",
                                            "--framer-font-family":
                                              '"DM Sans", "DM Sans Placeholder", sans-serif',
                                            "--framer-font-size": "14px",
                                            "--framer-font-weight": "500",
                                            "--framer-line-height": "130%",
                                            "--framer-text-color":
                                              "var(--extracted-r6o4lv, rgba(53, 48, 44, 0.5))",
                                          },
                                          children: /*#__PURE__*/ _jsx(Link, {
                                            href: "https://slingshotai.com/careers",
                                            motionChild: true,
                                            nodeId: "VkbAC3uqV",
                                            openInNewTab: true,
                                            relValues: [],
                                            scopeId: "O6t7eSwWb",
                                            smoothScroll: false,
                                            children: /*#__PURE__*/ _jsx(
                                              motion.a,
                                              {
                                                className:
                                                  "framer-styles-preset-1b2izic",
                                                "data-styles-preset":
                                                  "A9EvreP5V",
                                                children: "Join our team",
                                              }
                                            ),
                                          }),
                                        }),
                                      }
                                    ),
                                    className: "framer-y926ef",
                                    fonts: ["GF;DM Sans-500"],
                                    layoutDependency: layoutDependency,
                                    layoutId: "VkbAC3uqV",
                                    style: {
                                      "--extracted-r6o4lv":
                                        "rgba(53, 48, 44, 0.5)",
                                    },
                                    verticalAlignment: "top",
                                    whileHover: animation,
                                    withExternalLayout: true,
                                  }),
                                  /*#__PURE__*/ _jsx(RichText, {
                                    __fromCanvasComponent: true,
                                    children: /*#__PURE__*/ _jsx(
                                      React.Fragment,
                                      {
                                        children: /*#__PURE__*/ _jsx(motion.p, {
                                          dir: "auto",
                                          style: {
                                            "--font-selector":
                                              "R0Y7RE0gU2Fucy01MDA=",
                                            "--framer-font-family":
                                              '"DM Sans", "DM Sans Placeholder", sans-serif',
                                            "--framer-font-size": "14px",
                                            "--framer-font-weight": "500",
                                            "--framer-line-height": "130%",
                                            "--framer-text-color":
                                              "var(--extracted-r6o4lv, var(--token-0ecaa262-9aac-4113-a5a5-5bfcb0d17214, rgb(53, 48, 43)))",
                                          },
                                          children: /*#__PURE__*/ _jsx(Link, {
                                            href: "mailto:support@talktoash.com",
                                            motionChild: true,
                                            nodeId: "GwUD9snmB",
                                            openInNewTab: true,
                                            relValues: [],
                                            scopeId: "O6t7eSwWb",
                                            smoothScroll: false,
                                            children: /*#__PURE__*/ _jsx(
                                              motion.a,
                                              {
                                                className:
                                                  "framer-styles-preset-1b2izic",
                                                "data-styles-preset":
                                                  "A9EvreP5V",
                                                children:
                                                  "support@talktoash.com",
                                              }
                                            ),
                                          }),
                                        }),
                                      }
                                    ),
                                    className: "framer-kmvab9",
                                    fonts: ["GF;DM Sans-500"],
                                    layoutDependency: layoutDependency,
                                    layoutId: "GwUD9snmB",
                                    style: {
                                      "--extracted-r6o4lv":
                                        "var(--token-0ecaa262-9aac-4113-a5a5-5bfcb0d17214, rgb(53, 48, 43))",
                                    },
                                    verticalAlignment: "top",
                                    whileHover: animation,
                                    withExternalLayout: true,
                                  }),
                                  /*#__PURE__*/ _jsx(RichText, {
                                    __fromCanvasComponent: true,
                                    children: /*#__PURE__*/ _jsx(
                                      React.Fragment,
                                      {
                                        children: /*#__PURE__*/ _jsx(motion.p, {
                                          dir: "auto",
                                          style: {
                                            "--font-selector":
                                              "R0Y7RE0gU2Fucy01MDA=",
                                            "--framer-font-family":
                                              '"DM Sans", "DM Sans Placeholder", sans-serif',
                                            "--framer-font-size": "14px",
                                            "--framer-font-weight": "500",
                                            "--framer-line-height": "130%",
                                            "--framer-text-color":
                                              "var(--extracted-r6o4lv, var(--token-0ecaa262-9aac-4113-a5a5-5bfcb0d17214, rgb(53, 48, 43)))",
                                          },
                                          children: /*#__PURE__*/ _jsx(Link, {
                                            href: "mailto:press@slingshotai.com",
                                            motionChild: true,
                                            nodeId: "YEickFIoR",
                                            openInNewTab: true,
                                            relValues: [],
                                            scopeId: "O6t7eSwWb",
                                            smoothScroll: false,
                                            children: /*#__PURE__*/ _jsx(
                                              motion.a,
                                              {
                                                className:
                                                  "framer-styles-preset-1b2izic",
                                                "data-styles-preset":
                                                  "A9EvreP5V",
                                                children:
                                                  "press@slingshotai.com",
                                              }
                                            ),
                                          }),
                                        }),
                                      }
                                    ),
                                    className: "framer-1qlncnu",
                                    fonts: ["GF;DM Sans-500"],
                                    layoutDependency: layoutDependency,
                                    layoutId: "YEickFIoR",
                                    style: {
                                      "--extracted-r6o4lv":
                                        "var(--token-0ecaa262-9aac-4113-a5a5-5bfcb0d17214, rgb(53, 48, 43))",
                                    },
                                    verticalAlignment: "top",
                                    whileHover: animation,
                                    withExternalLayout: true,
                                  }),
                                ],
                              }),
                            }),
                          ],
                        }),
                      }),
                    ],
                  }),
                  /*#__PURE__*/ _jsx(motion.div, {
                    className: "framer-l4n3bd",
                    layoutDependency: layoutDependency,
                    layoutId: "owJ3uL9Ht",
                    style: { backgroundColor: "rgba(53, 48, 44, 0.1)" },
                  }),
                  /*#__PURE__*/ _jsxs(motion.div, {
                    className: "framer-rk5a4b",
                    "data-framer-name": "Support",
                    layoutDependency: layoutDependency,
                    layoutId: "K3tRcpxZS",
                    children: [
                      /*#__PURE__*/ _jsx(RichText, {
                        __fromCanvasComponent: true,
                        children: /*#__PURE__*/ _jsx(React.Fragment, {
                          children: /*#__PURE__*/ _jsx(motion.p, {
                            style: {
                              "--font-selector": "R0Y7RE0gU2Fucy02MDA=",
                              "--framer-font-family":
                                '"DM Sans", "DM Sans Placeholder", sans-serif',
                              "--framer-font-size": "12px",
                              "--framer-font-weight": "600",
                              "--framer-letter-spacing": "0.1em",
                              "--framer-line-height": "130%",
                              "--framer-text-color":
                                "var(--extracted-r6o4lv, var(--token-0ecaa262-9aac-4113-a5a5-5bfcb0d17214, rgb(53, 48, 43)))",
                            },
                            children: "ACKNOWLEDGMENT",
                          }),
                        }),
                        className: "framer-jfyg21",
                        fonts: ["GF;DM Sans-600"],
                        layoutDependency: layoutDependency,
                        layoutId: "tdtQXfvwo",
                        style: {
                          "--extracted-r6o4lv":
                            "var(--token-0ecaa262-9aac-4113-a5a5-5bfcb0d17214, rgb(53, 48, 43))",
                          "--framer-link-text-color": "rgb(0, 153, 255)",
                          "--framer-link-text-decoration": "underline",
                        },
                        verticalAlignment: "top",
                        withExternalLayout: true,
                      }),
                      /*#__PURE__*/ _jsx(RichText, {
                        __fromCanvasComponent: true,
                        children: /*#__PURE__*/ _jsx(React.Fragment, {
                          children: /*#__PURE__*/ _jsxs(motion.p, {
                            dir: "auto",
                            style: {
                              "--font-selector": "R0Y7RE0gU2Fucy0zMDA=",
                              "--framer-font-family":
                                '"DM Sans", "DM Sans Placeholder", sans-serif',
                              "--framer-font-size": "14px",
                              "--framer-font-weight": "300",
                              "--framer-line-height": "150%",
                              "--framer-text-color":
                                "var(--extracted-r6o4lv, var(--token-0ecaa262-9aac-4113-a5a5-5bfcb0d17214, rgb(53, 48, 43)))",
                            },
                            children: [
                              "Ash is not designed to be used in crisis. If you are in crisis, please seek out professional help, or a crisis line. You can find resources at ",
                              /*#__PURE__*/ _jsx(Link, {
                                href: "https://findahelpline.com/",
                                motionChild: true,
                                nodeId: "STI2jVw2F",
                                openInNewTab: true,
                                relValues: [],
                                scopeId: "O6t7eSwWb",
                                smoothScroll: false,
                                children: /*#__PURE__*/ _jsx(motion.a, {
                                  className: "framer-styles-preset-1yw13q7",
                                  "data-styles-preset": "Kz9GWIUzc",
                                  children: "www.findahelpline.com.",
                                }),
                              }),
                            ],
                          }),
                        }),
                        className: "framer-ef3297",
                        fonts: ["GF;DM Sans-300"],
                        layoutDependency: layoutDependency,
                        layoutId: "STI2jVw2F",
                        style: {
                          "--extracted-r6o4lv":
                            "var(--token-0ecaa262-9aac-4113-a5a5-5bfcb0d17214, rgb(53, 48, 43))",
                        },
                        verticalAlignment: "top",
                        withExternalLayout: true,
                      }),
                    ],
                  }),
                  /*#__PURE__*/ _jsx(motion.div, {
                    className: "framer-1obnk0h",
                    layoutDependency: layoutDependency,
                    layoutId: "FAET9xx4f",
                    style: { backgroundColor: "rgba(53, 48, 44, 0.1)" },
                  }),
                  /*#__PURE__*/ _jsxs(motion.div, {
                    className: "framer-sttecb",
                    layoutDependency: layoutDependency,
                    layoutId: "UwWuh9c3o",
                    children: [
                      /*#__PURE__*/ _jsx(RichText, {
                        __fromCanvasComponent: true,
                        children: /*#__PURE__*/ _jsx(React.Fragment, {
                          children: /*#__PURE__*/ _jsx(motion.p, {
                            style: {
                              "--font-selector": "R0Y7RE0gU2Fucy0zMDA=",
                              "--framer-font-family":
                                '"DM Sans", "DM Sans Placeholder", sans-serif',
                              "--framer-font-size": "14px",
                              "--framer-font-weight": "300",
                              "--framer-line-height": "130%",
                              "--framer-text-color":
                                "var(--extracted-r6o4lv, var(--token-0ecaa262-9aac-4113-a5a5-5bfcb0d17214, rgb(53, 48, 43)))",
                            },
                            children: "\xa9 Slingshot AI 2026",
                          }),
                        }),
                        className: "framer-rzme2v",
                        fonts: ["GF;DM Sans-300"],
                        layoutDependency: layoutDependency,
                        layoutId: "siTOqLcww",
                        style: {
                          "--extracted-r6o4lv":
                            "var(--token-0ecaa262-9aac-4113-a5a5-5bfcb0d17214, rgb(53, 48, 43))",
                          "--framer-link-text-color": "rgb(0, 153, 255)",
                          "--framer-link-text-decoration": "underline",
                        },
                        verticalAlignment: "top",
                        withExternalLayout: true,
                      }),
                      /*#__PURE__*/ _jsxs(motion.div, {
                        className: "framer-19w7vur",
                        layoutDependency: layoutDependency,
                        layoutId: "E2s1xSGhq",
                        children: [
                          /*#__PURE__*/ _jsx(Link, {
                            href: { webPageId: "NGo8nS5pR" },
                            motionChild: true,
                            nodeId: "ntri5YZMZ",
                            openInNewTab: false,
                            scopeId: "O6t7eSwWb",
                            children: /*#__PURE__*/ _jsx(motion.a, {
                              className: "framer-c31n08 framer-nyt7b7",
                              layoutDependency: layoutDependency,
                              layoutId: "ntri5YZMZ",
                              children: /*#__PURE__*/ _jsx(RichText, {
                                __fromCanvasComponent: true,
                                children: /*#__PURE__*/ _jsx(React.Fragment, {
                                  children: /*#__PURE__*/ _jsx(motion.p, {
                                    style: {
                                      "--font-selector": "R0Y7RE0gU2Fucy0zMDA=",
                                      "--framer-font-family":
                                        '"DM Sans", "DM Sans Placeholder", sans-serif',
                                      "--framer-font-size": "14px",
                                      "--framer-font-weight": "300",
                                      "--framer-text-color":
                                        "var(--extracted-r6o4lv, var(--token-0ecaa262-9aac-4113-a5a5-5bfcb0d17214, rgb(53, 48, 43)))",
                                    },
                                    children: "End User License Agreement",
                                  }),
                                }),
                                className: "framer-nedu97",
                                fonts: ["GF;DM Sans-300"],
                                layoutDependency: layoutDependency,
                                layoutId: "zaj9L29dV",
                                style: {
                                  "--extracted-r6o4lv":
                                    "var(--token-0ecaa262-9aac-4113-a5a5-5bfcb0d17214, rgb(53, 48, 43))",
                                  "--framer-link-text-color":
                                    "rgb(0, 153, 255)",
                                  "--framer-link-text-decoration": "underline",
                                },
                                verticalAlignment: "top",
                                withExternalLayout: true,
                              }),
                            }),
                          }),
                          /*#__PURE__*/ _jsx(Link, {
                            href: { webPageId: "VhE4B5Tmw" },
                            motionChild: true,
                            nodeId: "dillu74Mu",
                            openInNewTab: false,
                            scopeId: "O6t7eSwWb",
                            children: /*#__PURE__*/ _jsx(motion.a, {
                              className: "framer-1lvjb2e framer-nyt7b7",
                              layoutDependency: layoutDependency,
                              layoutId: "dillu74Mu",
                              children: /*#__PURE__*/ _jsx(RichText, {
                                __fromCanvasComponent: true,
                                children: /*#__PURE__*/ _jsx(React.Fragment, {
                                  children: /*#__PURE__*/ _jsx(motion.p, {
                                    style: {
                                      "--font-selector": "R0Y7RE0gU2Fucy0zMDA=",
                                      "--framer-font-family":
                                        '"DM Sans", "DM Sans Placeholder", sans-serif',
                                      "--framer-font-size": "14px",
                                      "--framer-font-weight": "300",
                                      "--framer-text-color":
                                        "var(--extracted-r6o4lv, var(--token-0ecaa262-9aac-4113-a5a5-5bfcb0d17214, rgb(53, 48, 43)))",
                                    },
                                    children: "Privacy Policy",
                                  }),
                                }),
                                className: "framer-kvg1ix",
                                fonts: ["GF;DM Sans-300"],
                                layoutDependency: layoutDependency,
                                layoutId: "jsPuGifXS",
                                style: {
                                  "--extracted-r6o4lv":
                                    "var(--token-0ecaa262-9aac-4113-a5a5-5bfcb0d17214, rgb(53, 48, 43))",
                                  "--framer-link-text-color":
                                    "rgb(0, 153, 255)",
                                  "--framer-link-text-decoration": "underline",
                                },
                                verticalAlignment: "top",
                                withExternalLayout: true,
                              }),
                            }),
                          }),
                          /*#__PURE__*/ _jsx(Link, {
                            href: { webPageId: "XvWWjMa71" },
                            motionChild: true,
                            nodeId: "W_YgfjWeH",
                            openInNewTab: false,
                            scopeId: "O6t7eSwWb",
                            children: /*#__PURE__*/ _jsx(motion.a, {
                              className: "framer-9ic4hc framer-nyt7b7",
                              "data-framer-name": "Health Notice Link",
                              layoutDependency: layoutDependency,
                              layoutId: "W_YgfjWeH",
                              children: /*#__PURE__*/ _jsx(RichText, {
                                __fromCanvasComponent: true,
                                children: /*#__PURE__*/ _jsx(React.Fragment, {
                                  children: /*#__PURE__*/ _jsx(motion.p, {
                                    dir: "auto",
                                    style: {
                                      "--font-selector": "R0Y7RE0gU2Fucy0zMDA=",
                                      "--framer-font-family":
                                        '"DM Sans", "DM Sans Placeholder", sans-serif',
                                      "--framer-font-size": "14px",
                                      "--framer-font-weight": "300",
                                      "--framer-text-color":
                                        "var(--extracted-r6o4lv, var(--token-0ecaa262-9aac-4113-a5a5-5bfcb0d17214, rgb(53, 48, 43)))",
                                    },
                                    children:
                                      "Consumer Health Data Privacy Notice",
                                  }),
                                }),
                                className: "framer-ovtihu",
                                fonts: ["GF;DM Sans-300"],
                                layoutDependency: layoutDependency,
                                layoutId: "w6eX4QoAa",
                                style: {
                                  "--extracted-r6o4lv":
                                    "var(--token-0ecaa262-9aac-4113-a5a5-5bfcb0d17214, rgb(53, 48, 43))",
                                  "--framer-link-text-color":
                                    "rgb(0, 153, 255)",
                                  "--framer-link-text-decoration": "underline",
                                },
                                verticalAlignment: "top",
                                withExternalLayout: true,
                              }),
                            }),
                          }),
                        ],
                      }),
                    ],
                  }),
                ],
              }),
            }),
          ],
        }),
      }),
    }),
  });
});
const css = [
  ".framer-CRn1M.framer-nyt7b7, .framer-CRn1M .framer-nyt7b7 { display: block; }",
  ".framer-CRn1M.framer-45gk8g { align-content: center; align-items: center; display: flex; flex-direction: column; flex-wrap: nowrap; gap: 48px; height: min-content; justify-content: center; overflow: hidden; padding: 0px; position: relative; width: 1200px; }",
  ".framer-CRn1M .framer-kc03lq { align-content: center; align-items: center; display: flex; flex: none; flex-direction: column; flex-wrap: nowrap; gap: 10px; height: min-content; justify-content: center; overflow: visible; padding: 0px; position: relative; width: 100%; }",
  ".framer-CRn1M .framer-19bt5g6 { align-content: center; align-items: center; display: flex; flex: none; flex-direction: column; flex-wrap: nowrap; gap: 64px; height: min-content; justify-content: center; overflow: hidden; padding: 128px 0px 128px 0px; position: relative; width: 1000px; will-change: var(--framer-will-change-override, transform); }",
  ".framer-CRn1M .framer-1o0x3a7 { align-content: center; align-items: center; display: flex; flex: none; flex-direction: column; flex-wrap: nowrap; gap: 24px; height: min-content; justify-content: center; overflow: hidden; padding: 0px; position: relative; width: 600px; }",
  ".framer-CRn1M .framer-1rd366y, .framer-CRn1M .framer-7v9337 { flex: none; height: auto; position: relative; white-space: pre-wrap; width: 100%; word-break: break-word; word-wrap: break-word; }",
  ".framer-CRn1M .framer-lr6ox5-container { flex: none; height: 48px; position: relative; width: 144px; }",
  ".framer-CRn1M .framer-1s3h76o { align-content: center; align-items: center; display: flex; flex: none; flex-direction: column; flex-wrap: nowrap; gap: 24px; height: min-content; justify-content: flex-start; overflow: visible; padding: 48px 0px 48px 0px; position: relative; width: 100%; }",
  ".framer-CRn1M .framer-1g7ar5k { align-content: flex-start; align-items: flex-start; display: flex; flex: none; flex-direction: column; flex-wrap: nowrap; gap: 28px; height: min-content; justify-content: center; overflow: visible; padding: 0px; position: relative; width: 1000px; }",
  ".framer-CRn1M .framer-17w9zn4 { align-content: flex-start; align-items: flex-start; display: flex; flex: none; flex-direction: row; flex-wrap: nowrap; height: min-content; justify-content: space-between; overflow: hidden; padding: 0px; position: relative; width: 100%; }",
  ".framer-CRn1M .framer-12tdyuf { align-content: flex-start; align-items: flex-start; display: flex; flex: 1 0 0px; flex-direction: column; flex-wrap: nowrap; gap: 16px; height: min-content; justify-content: center; overflow: hidden; padding: 0px; position: relative; width: 1px; }",
  ".framer-CRn1M .framer-1i1fe27 { height: 24px; position: relative; width: 52px; }",
  ".framer-CRn1M .framer-e7r9t9 { height: 23px; left: 0px; position: absolute; top: 1px; width: 23px; }",
  ".framer-CRn1M .framer-iuk3s1 { height: 11px; left: 7px; position: absolute; top: 4px; width: 8px; }",
  ".framer-CRn1M .framer-1cv9025 { height: 16px; left: 21px; position: absolute; top: 8px; width: 14px; }",
  ".framer-CRn1M .framer-13kmlwq { height: 24px; left: 35px; position: absolute; top: 0px; width: 17px; }",
  ".framer-CRn1M .framer-jablm { align-content: center; align-items: center; display: flex; flex: none; flex-direction: row; flex-wrap: nowrap; gap: 8px; height: min-content; justify-content: center; overflow: hidden; padding: 0px; position: relative; width: min-content; }",
  ".framer-CRn1M .framer-1j2a3xy, .framer-CRn1M .framer-1xrq5wx, .framer-CRn1M .framer-mnnosz, .framer-CRn1M .framer-hwzf0h, .framer-CRn1M .framer-v8rjm3 { align-content: center; align-items: center; display: flex; flex: none; flex-direction: row; flex-wrap: nowrap; gap: 10px; height: min-content; justify-content: center; overflow: visible; padding: 0px; position: relative; text-decoration: none; width: min-content; }",
  ".framer-CRn1M .framer-y2r9di, .framer-CRn1M .framer-1mlkvu4, .framer-CRn1M .framer-34edvh, .framer-CRn1M .framer-3r19sq, .framer-CRn1M .framer-1vs7hie { flex: none; height: auto; position: relative; width: 24px; will-change: var(--framer-will-change-effect-override, transform); }",
  ".framer-CRn1M .framer-6egu0i { align-content: flex-end; align-items: flex-end; display: flex; flex: 1 0 0px; flex-direction: column; flex-wrap: nowrap; gap: 8px; height: min-content; justify-content: center; overflow: hidden; padding: 0px; position: relative; width: 1px; }",
  ".framer-CRn1M .framer-1mlrs5y { align-content: flex-start; align-items: flex-start; display: flex; flex: none; flex-direction: column; flex-wrap: nowrap; gap: 16px; height: min-content; justify-content: center; overflow: visible; padding: 0px; position: relative; width: min-content; }",
  ".framer-CRn1M .framer-22165p, .framer-CRn1M .framer-jfyg21, .framer-CRn1M .framer-nedu97, .framer-CRn1M .framer-kvg1ix, .framer-CRn1M .framer-ovtihu { flex: none; height: auto; position: relative; white-space: pre; width: auto; }",
  ".framer-CRn1M .framer-1og3o1n { align-content: flex-start; align-items: flex-start; display: flex; flex: none; flex-direction: column; flex-wrap: nowrap; gap: 8px; height: min-content; justify-content: center; overflow: visible; padding: 0px; position: relative; width: min-content; }",
  ".framer-CRn1M .framer-zw0w8w { align-content: flex-start; align-items: flex-start; display: flex; flex: none; flex-direction: column; flex-wrap: nowrap; gap: 4px; height: min-content; justify-content: center; overflow: visible; padding: 0px; position: relative; width: min-content; }",
  ".framer-CRn1M .framer-y926ef, .framer-CRn1M .framer-kmvab9, .framer-CRn1M .framer-1qlncnu { flex: none; height: auto; position: relative; white-space: pre; width: auto; will-change: var(--framer-will-change-effect-override, transform); }",
  ".framer-CRn1M .framer-l4n3bd, .framer-CRn1M .framer-1obnk0h { flex: none; height: 1px; overflow: visible; position: relative; width: 100%; }",
  ".framer-CRn1M .framer-rk5a4b { align-content: flex-start; align-items: flex-start; display: flex; flex: none; flex-direction: column; flex-wrap: nowrap; gap: 8px; height: min-content; justify-content: center; overflow: hidden; padding: 0px; position: relative; width: 100%; }",
  ".framer-CRn1M .framer-ef3297 { flex: none; height: auto; position: relative; white-space: pre-wrap; width: 600px; word-break: break-word; word-wrap: break-word; }",
  ".framer-CRn1M .framer-sttecb { align-content: center; align-items: center; display: flex; flex: none; flex-direction: row; flex-wrap: nowrap; gap: 24px; height: min-content; justify-content: center; overflow: visible; padding: 0px; position: relative; width: 100%; }",
  ".framer-CRn1M .framer-rzme2v { flex: 1 0 0px; height: auto; position: relative; white-space: pre-wrap; width: 1px; word-break: break-word; word-wrap: break-word; }",
  ".framer-CRn1M .framer-19w7vur { align-content: center; align-items: center; display: flex; flex: none; flex-direction: row; flex-wrap: nowrap; gap: 10px; height: min-content; justify-content: center; overflow: visible; padding: 0px; position: relative; width: min-content; }",
  ".framer-CRn1M .framer-c31n08, .framer-CRn1M .framer-1lvjb2e, .framer-CRn1M .framer-9ic4hc { align-content: center; align-items: center; display: flex; flex: none; flex-direction: row; flex-wrap: nowrap; gap: 10px; height: min-content; justify-content: center; overflow: visible; padding: 4px; position: relative; text-decoration: none; width: min-content; }",
  ".framer-CRn1M.framer-v-vu3yea.framer-45gk8g { width: 810px; }",
  ".framer-CRn1M.framer-v-vu3yea .framer-kc03lq { flex-direction: row; padding: 0px 16px 0px 16px; }",
  ".framer-CRn1M.framer-v-vu3yea .framer-19bt5g6 { flex: 1 0 0px; padding: 128px 16px 128px 16px; width: 1px; }",
  ".framer-CRn1M.framer-v-vu3yea .framer-1s3h76o { padding: 48px 24px 48px 24px; }",
  ".framer-CRn1M.framer-v-vu3yea .framer-1g7ar5k, .framer-CRn1M.framer-v-tqwtez .framer-1o0x3a7, .framer-CRn1M.framer-v-tqwtez .framer-ef3297 { width: 100%; }",
  ".framer-CRn1M.framer-v-tqwtez.framer-45gk8g { width: 390px; }",
  ".framer-CRn1M.framer-v-tqwtez .framer-kc03lq { padding: 0px 16px 0px 16px; }",
  ".framer-CRn1M.framer-v-tqwtez .framer-19bt5g6 { padding: 128px 16px 128px 16px; width: 100%; }",
  ".framer-CRn1M.framer-v-tqwtez .framer-1g7ar5k { padding: 0px 16px 0px 16px; width: 100%; }",
  ".framer-CRn1M.framer-v-tqwtez .framer-17w9zn4 { flex-direction: column; gap: 32px; justify-content: flex-start; }",
  ".framer-CRn1M.framer-v-tqwtez .framer-12tdyuf { flex: none; width: 100%; }",
  ".framer-CRn1M.framer-v-tqwtez .framer-6egu0i { align-content: flex-start; align-items: flex-start; flex: none; width: 100%; }",
  ".framer-CRn1M.framer-v-tqwtez .framer-1mlrs5y { gap: 20px; }",
  ".framer-CRn1M.framer-v-tqwtez .framer-zw0w8w { gap: 8px; }",
  ".framer-CRn1M.framer-v-tqwtez .framer-rk5a4b { gap: 12px; padding: 0px 16px 0px 0px; }",
  ".framer-CRn1M.framer-v-tqwtez .framer-sttecb { align-content: flex-start; align-items: flex-start; flex-direction: column; }",
  ".framer-CRn1M.framer-v-tqwtez .framer-rzme2v { flex: none; order: 1; width: 100%; }",
  ".framer-CRn1M.framer-v-tqwtez .framer-19w7vur { align-content: flex-start; align-items: flex-start; flex-direction: column; gap: 8px; height: 76px; order: 0; width: 201px; }",
  ...sharedStyle.css,
  ...sharedStyle1.css,
  ...sharedStyle2.css,
  ...sharedStyle3.css,
  '.framer-CRn1M[data-border="true"]::after, .framer-CRn1M [data-border="true"]::after { content: ""; border-width: var(--border-top-width, 0) var(--border-right-width, 0) var(--border-bottom-width, 0) var(--border-left-width, 0); border-color: var(--border-color, none); border-style: var(--border-style, none); width: 100%; height: 100%; position: absolute; box-sizing: border-box; left: 0; top: 0; border-radius: inherit; corner-shape: inherit; pointer-events: none; }',
];
/**
 * This is a generated Framer component.
 * @framerIntrinsicHeight 937
 * @framerIntrinsicWidth 1200
 * @framerCanvasComponentVariantDetails {"propertyName":"variant","data":{"default":{"layout":["fixed","auto"]},"TrOL0ndGc":{"layout":["fixed","auto"]},"D35XkzQGc":{"layout":["fixed","auto"]}}}
 * @framerVariables {"p5B5KxpAb":"cTA"}
 * @framerImmutableVariables true
 * @framerDisplayContentsDiv false
 * @framerAutoSizeImages true
 * @framerComponentViewportWidth true
 * @framerColorSyntax true
 */ const FramerO6t7eSwWb = withCSS(Component, css, "framer-CRn1M");
export default FramerO6t7eSwWb;
FramerO6t7eSwWb.displayName = "Footer";
FramerO6t7eSwWb.defaultProps = { height: 937, width: 1200 };
addPropertyControls(FramerO6t7eSwWb, {
  variant: {
    options: ["nDxwOaqqO", "TrOL0ndGc", "D35XkzQGc"],
    optionTitles: ["Desktop", "Tablet", "Phone"],
    title: "Variant",
    type: ControlType.Enum,
  },
  p5B5KxpAb: { defaultValue: true, title: "CTA", type: ControlType.Boolean },
  onp5B5KxpAbChange: { changes: "p5B5KxpAb", type: ControlType.ChangeHandler },
});
addFonts(
  FramerO6t7eSwWb,
  [
    {
      explicitInter: true,
      fonts: [
        {
          cssFamilyName: "Inter",
          source: "framer",
          style: "normal",
          uiFamilyName: "Inter",
          unicodeRange:
            "U+0460-052F, U+1C80-1C88, U+20B4, U+2DE0-2DFF, U+A640-A69F, U+FE2E-FE2F",
          url: "https://framerusercontent.com/assets/5vvr9Vy74if2I6bQbJvbw7SY1pQ.woff2",
          weight: "400",
        },
        {
          cssFamilyName: "Inter",
          source: "framer",
          style: "normal",
          uiFamilyName: "Inter",
          unicodeRange: "U+0301, U+0400-045F, U+0490-0491, U+04B0-04B1, U+2116",
          url: "https://framerusercontent.com/assets/EOr0mi4hNtlgWNn9if640EZzXCo.woff2",
          weight: "400",
        },
        {
          cssFamilyName: "Inter",
          source: "framer",
          style: "normal",
          uiFamilyName: "Inter",
          unicodeRange: "U+1F00-1FFF",
          url: "https://framerusercontent.com/assets/Y9k9QrlZAqio88Klkmbd8VoMQc.woff2",
          weight: "400",
        },
        {
          cssFamilyName: "Inter",
          source: "framer",
          style: "normal",
          uiFamilyName: "Inter",
          unicodeRange: "U+0370-03FF",
          url: "https://framerusercontent.com/assets/OYrD2tBIBPvoJXiIHnLoOXnY9M.woff2",
          weight: "400",
        },
        {
          cssFamilyName: "Inter",
          source: "framer",
          style: "normal",
          uiFamilyName: "Inter",
          unicodeRange:
            "U+0100-024F, U+0259, U+1E00-1EFF, U+2020, U+20A0-20AB, U+20AD-20CF, U+2113, U+2C60-2C7F, U+A720-A7FF",
          url: "https://framerusercontent.com/assets/JeYwfuaPfZHQhEG8U5gtPDZ7WQ.woff2",
          weight: "400",
        },
        {
          cssFamilyName: "Inter",
          source: "framer",
          style: "normal",
          uiFamilyName: "Inter",
          unicodeRange:
            "U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+2000-206F, U+2070, U+2074-207E, U+2080-208E, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD",
          url: "https://framerusercontent.com/assets/GrgcKwrN6d3Uz8EwcLHZxwEfC4.woff2",
          weight: "400",
        },
        {
          cssFamilyName: "Inter",
          source: "framer",
          style: "normal",
          uiFamilyName: "Inter",
          unicodeRange:
            "U+0102-0103, U+0110-0111, U+0128-0129, U+0168-0169, U+01A0-01A1, U+01AF-01B0, U+1EA0-1EF9, U+20AB",
          url: "https://framerusercontent.com/assets/b6Y37FthZeALduNqHicBT6FutY.woff2",
          weight: "400",
        },
        {
          cssFamilyName: "DM Sans",
          source: "google",
          style: "normal",
          uiFamilyName: "DM Sans",
          url: "https://fonts.gstatic.com/s/dmsans/v17/rP2tp2ywxg089UriI5-g4vlH9VoD8CmcqZG40F9JadbnoEwAfJthS2f3ZGMZpg.woff2",
          weight: "600",
        },
        {
          cssFamilyName: "DM Sans",
          source: "google",
          style: "normal",
          uiFamilyName: "DM Sans",
          url: "https://fonts.gstatic.com/s/dmsans/v17/rP2tp2ywxg089UriI5-g4vlH9VoD8CmcqZG40F9JadbnoEwAkJxhS2f3ZGMZpg.woff2",
          weight: "500",
        },
        {
          cssFamilyName: "DM Sans",
          source: "google",
          style: "normal",
          uiFamilyName: "DM Sans",
          url: "https://fonts.gstatic.com/s/dmsans/v17/rP2tp2ywxg089UriI5-g4vlH9VoD8CmcqZG40F9JadbnoEwA_JxhS2f3ZGMZpg.woff2",
          weight: "300",
        },
      ],
    },
    ...DownloadButtonFonts,
    ...InstagramLogoFonts,
    ...FacebookLogoFonts,
    ...RedditLogoFonts,
    ...TwitterLogoFonts,
    ...YoutubeLogoFonts,
    ...getFontsFromSharedStyle(sharedStyle.fonts),
    ...getFontsFromSharedStyle(sharedStyle1.fonts),
    ...getFontsFromSharedStyle(sharedStyle2.fonts),
    ...getFontsFromSharedStyle(sharedStyle3.fonts),
  ],
  { supportsExplicitInterCodegen: true }
);
FramerO6t7eSwWb.loader = {
  load: (props, context) => {
    return runTasksWithYield(
      [() => forwardLoader(DownloadButton, {}, context)],
      context
    );
  },
};
export const __FramerMetadata__ = {
  exports: {
    default: {
      type: "reactComponent",
      name: "FramerO6t7eSwWb",
      slots: [],
      annotations: {
        framerIntrinsicHeight: "937",
        framerComponentViewportWidth: "true",
        framerAutoSizeImages: "true",
        framerContractVersion: "1",
        framerCanvasComponentVariantDetails:
          '{"propertyName":"variant","data":{"default":{"layout":["fixed","auto"]},"TrOL0ndGc":{"layout":["fixed","auto"]},"D35XkzQGc":{"layout":["fixed","auto"]}}}',
        framerVariables: '{"p5B5KxpAb":"cTA"}',
        framerIntrinsicWidth: "1200",
        framerDisplayContentsDiv: "false",
        framerImmutableVariables: "true",
        framerColorSyntax: "true",
      },
    },
    Props: { type: "tsType", annotations: { framerContractVersion: "1" } },
    __FramerMetadata__: { type: "variable" },
  },
};
//# sourceMappingURL=./O6t7eSwWb.map
