// Generated by Framer (7e6a191)
import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import {
  addFonts,
  addPropertyControls,
  ComponentViewportProvider,
  ControlType,
  cx,
  forwardLoader,
  getFonts,
  RichText,
  runTasksWithYield,
  SmartComponentScopedContainer,
  useActiveVariantCallback,
  useComponentViewport,
  useLocaleInfo,
  useVariantState,
  withCSS,
  withFX,
} from "framer";
import { LayoutGroup, motion, MotionConfigContext } from "framer-motion";
import * as React from "react";
import { useRef } from "react";
import PlusIcon from "https://framerusercontent.com/modules/deEoWRtdSzowH2wa4wSm/jqrPOatFYdw1TC963fQV/yczviJyPO.js";
const PlusIconFonts = getFonts(PlusIcon);
const MotionDivWithFX = withFX(motion.div);
const enabledGestures = { CwvHPtV1t: { hover: true } };
const cycleOrder = ["Is_0zeX5t", "CwvHPtV1t", "jhF3fI41X", "atF16Hnec"];
const serializationHash = "framer-1vWZc";
const variantClassNames = {
  atF16Hnec: "framer-v-3hmb5m",
  CwvHPtV1t: "framer-v-2jeths",
  Is_0zeX5t: "framer-v-1xg346n",
  jhF3fI41X: "framer-v-1gc2b9s",
};
function addPropertyOverrides(overrides, ...variants) {
  const nextOverrides = {};
  variants?.forEach(
    (variant) => variant && Object.assign(nextOverrides, overrides[variant])
  );
  return nextOverrides;
}
const vd59XDbg4 = undefined;
const m1wBZJAoM = undefined;
const animation = {
  opacity: 0,
  rotate: 0,
  rotateX: 0,
  rotateY: 0,
  scale: 1,
  skewX: 0,
  skewY: 0,
  x: 0,
  y: 24,
};
const transition1 = {
  damping: 50,
  delay: 0.1,
  mass: 1,
  stiffness: 250,
  type: "spring",
};
const animation1 = {
  opacity: 0,
  rotate: 0,
  rotateX: 0,
  rotateY: 0,
  scale: 1,
  skewX: 0,
  skewY: 0,
  transition: transition1,
  x: 0,
  y: 24,
};
const transition2 = {
  damping: 60,
  delay: 0,
  mass: 1,
  stiffness: 500,
  type: "spring",
};
const matchVariant = (...args) => {
  for (const arg of args) {
    if (arg && typeof arg === "string") return arg;
  }
  return undefined;
};
const Transition = ({ value, children }) => {
  const config = React.useContext(MotionConfigContext);
  const transition = value ?? config.transition;
  const contextValue = React.useMemo(
    () => ({ ...config, transition }),
    [JSON.stringify(transition)]
  );
  return /*#__PURE__*/ _jsx(MotionConfigContext.Provider, {
    value: contextValue,
    children: children,
  });
};
const humanReadableVariantMap = {
  Closed: "CwvHPtV1t",
  FAQMobileClosed: "atF16Hnec",
  FAQMobileOpen: "jhF3fI41X",
  Open: "Is_0zeX5t",
};
const Variants = motion.create(React.Fragment);
const getProps = ({ answer, height, id, question, width, ...props }) => {
  return {
    ...props,
    m1wBZJAoM:
      answer ??
      props.m1wBZJAoM ??
      "You can cancel your plan whenever you’d like. You’ll be downgraded to the free plan. You won’t be locked out of any projects that have paid plans.",
    variant:
      humanReadableVariantMap[props.variant] ?? props.variant ?? "Is_0zeX5t",
    vd59XDbg4:
      question ?? props.vd59XDbg4 ?? "Which pricing plan is right for me?",
  };
};
const createLayoutDependency = (props, variants) => {
  if (props.layoutDependency)
    return variants.join("-") + props.layoutDependency;
  return variants.join("-");
};
const Component = /*#__PURE__*/ React.forwardRef(function (props, ref) {
  const fallbackRef = useRef(null);
  const refBinding = ref ?? fallbackRef;
  const defaultLayoutId = React.useId();
  const { activeLocale, setLocale } = useLocaleInfo();
  const componentViewport = useComponentViewport();
  const {
    style,
    className,
    layoutId,
    variant,
    vd59XDbg4,
    m1wBZJAoM,
    ...restProps
  } = getProps(props);
  const {
    baseVariant,
    classNames,
    clearLoadingGesture,
    gestureHandlers,
    gestureVariant,
    isLoading,
    setGestureState,
    setVariant,
    variants,
  } = useVariantState({
    cycleOrder,
    defaultVariant: "Is_0zeX5t",
    enabledGestures,
    ref: refBinding,
    variant,
    variantClassNames,
  });
  const layoutDependency = createLayoutDependency(props, variants);
  const sharedStyleClassNames = [];
  const { activeVariantCallback, delay } =
    useActiveVariantCallback(baseVariant);
  const onTapguqj0g = activeVariantCallback(async (...args) => {
    setGestureState({ isPressed: false });
    setVariant("CwvHPtV1t");
  });
  const scopingClassNames = cx(serializationHash, ...sharedStyleClassNames);
  const onTap1imhlsm = activeVariantCallback(async (...args) => {
    setGestureState({ isPressed: false });
    setVariant("Is_0zeX5t");
  });
  const onTaplzvg2o = activeVariantCallback(async (...args) => {
    setGestureState({ isPressed: false });
    setVariant("atF16Hnec");
  });
  const onTap1x9u5z3 = activeVariantCallback(async (...args) => {
    setGestureState({ isPressed: false });
    setVariant("jhF3fI41X");
  });
  const isDisplayed = () => {
    if (gestureVariant === "CwvHPtV1t-hover") return false;
    if (["CwvHPtV1t", "atF16Hnec"].includes(baseVariant)) return false;
    return true;
  };
  return /*#__PURE__*/ _jsx(LayoutGroup, {
    id: layoutId ?? defaultLayoutId,
    children: /*#__PURE__*/ _jsx(Variants, {
      animate: variants,
      initial: false,
      children: /*#__PURE__*/ _jsx(Transition, {
        value: transition2,
        children: /*#__PURE__*/ _jsxs(MotionDivWithFX, {
          ...restProps,
          ...gestureHandlers,
          __framer__animate: { transition: transition1 },
          __framer__animateOnce: true,
          __framer__enter: animation,
          __framer__exit: animation1,
          __framer__styleAppearEffectEnabled: true,
          __framer__threshold: 0.5,
          __perspectiveFX: false,
          __smartComponentFX: true,
          __targetOpacity: 1,
          className: cx(
            scopingClassNames,
            "framer-1xg346n",
            className,
            classNames
          ),
          "data-framer-name": "Open",
          "data-highlight": true,
          layoutDependency: layoutDependency,
          layoutId: "Is_0zeX5t",
          onTap: onTapguqj0g,
          ref: refBinding,
          style: { ...style },
          ...addPropertyOverrides(
            {
              "CwvHPtV1t-hover": { __framer__exit: undefined },
              atF16Hnec: {
                "data-framer-name": "FAQMobileClosed",
                onTap: onTap1x9u5z3,
              },
              CwvHPtV1t: {
                __framer__exit: undefined,
                "data-framer-name": "Closed",
                onTap: onTap1imhlsm,
              },
              jhF3fI41X: {
                "data-framer-name": "FAQMobileOpen",
                onTap: onTaplzvg2o,
              },
            },
            baseVariant,
            gestureVariant
          ),
          children: [
            /*#__PURE__*/ _jsxs(motion.div, {
              className: "framer-17kwd86",
              "data-framer-name": "Question",
              layoutDependency: layoutDependency,
              layoutId: "oAjUVrTPb",
              children: [
                /*#__PURE__*/ _jsx(RichText, {
                  __fromCanvasComponent: true,
                  children: /*#__PURE__*/ _jsx(React.Fragment, {
                    children: /*#__PURE__*/ _jsx(motion.h3, {
                      style: {
                        "--font-selector": "R0Y7RE0gU2Fucy02MDA=",
                        "--framer-font-family":
                          '"DM Sans", "DM Sans Placeholder", sans-serif',
                        "--framer-font-size": "24px",
                        "--framer-font-weight": "600",
                        "--framer-letter-spacing": "-0.03em",
                        "--framer-line-height": "1.4em",
                        "--framer-text-color":
                          "var(--extracted-a0htzi, var(--token-0ecaa262-9aac-4113-a5a5-5bfcb0d17214, rgb(53, 48, 43)))",
                      },
                      children: "Which pricing plan is right for me?",
                    }),
                  }),
                  className: "framer-3vzzdf",
                  fonts: ["GF;DM Sans-600"],
                  layoutDependency: layoutDependency,
                  layoutId: "cACkO_ujA",
                  style: {
                    "--extracted-a0htzi":
                      "var(--token-0ecaa262-9aac-4113-a5a5-5bfcb0d17214, rgb(53, 48, 43))",
                    "--framer-link-text-color": "rgb(0, 153, 255)",
                    "--framer-link-text-decoration": "underline",
                  },
                  text: vd59XDbg4,
                  verticalAlignment: "top",
                  withExternalLayout: true,
                  ...addPropertyOverrides(
                    {
                      atF16Hnec: {
                        children: /*#__PURE__*/ _jsx(React.Fragment, {
                          children: /*#__PURE__*/ _jsx(motion.h3, {
                            style: {
                              "--font-selector": "R0Y7RE0gU2Fucy02MDA=",
                              "--framer-font-family":
                                '"DM Sans", "DM Sans Placeholder", sans-serif',
                              "--framer-font-size": "20px",
                              "--framer-font-weight": "600",
                              "--framer-letter-spacing": "-0.03em",
                              "--framer-line-height": "1.4em",
                              "--framer-text-color":
                                "var(--extracted-a0htzi, var(--token-0ecaa262-9aac-4113-a5a5-5bfcb0d17214, rgb(53, 48, 43)))",
                            },
                            children: "Which pricing plan is right for me?",
                          }),
                        }),
                      },
                      jhF3fI41X: {
                        children: /*#__PURE__*/ _jsx(React.Fragment, {
                          children: /*#__PURE__*/ _jsx(motion.h3, {
                            style: {
                              "--font-selector": "R0Y7RE0gU2Fucy02MDA=",
                              "--framer-font-family":
                                '"DM Sans", "DM Sans Placeholder", sans-serif',
                              "--framer-font-size": "20px",
                              "--framer-font-weight": "600",
                              "--framer-letter-spacing": "-0.03em",
                              "--framer-line-height": "1.4em",
                              "--framer-text-color":
                                "var(--extracted-a0htzi, var(--token-0ecaa262-9aac-4113-a5a5-5bfcb0d17214, rgb(53, 48, 43)))",
                            },
                            children: "Which pricing plan is right for me?",
                          }),
                        }),
                      },
                    },
                    baseVariant,
                    gestureVariant
                  ),
                }),
                /*#__PURE__*/ _jsx(ComponentViewportProvider, {
                  height: 32,
                  y: (componentViewport?.y || 0) + 0 + 0 + 0.8,
                  ...addPropertyOverrides(
                    {
                      atF16Hnec: { y: (componentViewport?.y || 0) + 0 + 0 + 0 },
                      jhF3fI41X: { y: (componentViewport?.y || 0) + 0 + 0 + 0 },
                    },
                    baseVariant,
                    gestureVariant
                  ),
                  children: /*#__PURE__*/ _jsx(SmartComponentScopedContainer, {
                    className: "framer-170zmkp-container",
                    layoutDependency: layoutDependency,
                    layoutId: "qiCkwUHiN-container",
                    nodeId: "qiCkwUHiN",
                    rendersWithMotion: true,
                    scopeId: "kQIC9ukuG",
                    style: { rotate: -180 },
                    children: /*#__PURE__*/ _jsx(PlusIcon, {
                      height: "100%",
                      id: "qiCkwUHiN",
                      layoutId: "qiCkwUHiN",
                      variant: matchVariant("B1LH91gFj"),
                      width: "100%",
                      ...addPropertyOverrides(
                        {
                          "CwvHPtV1t-hover": {
                            variant: matchVariant("tv3nU8XHS"),
                          },
                          atF16Hnec: { variant: matchVariant("dKQ0QYYHx") },
                          CwvHPtV1t: { variant: matchVariant("dKQ0QYYHx") },
                        },
                        baseVariant,
                        gestureVariant
                      ),
                    }),
                  }),
                }),
              ],
            }),
            isDisplayed() &&
              /*#__PURE__*/ _jsx(motion.div, {
                className: "framer-1qn57zt",
                "data-framer-name": "Answer",
                layoutDependency: layoutDependency,
                layoutId: "N8qkBpCUV",
                children: /*#__PURE__*/ _jsx(RichText, {
                  __fromCanvasComponent: true,
                  children: /*#__PURE__*/ _jsx(React.Fragment, {
                    children: /*#__PURE__*/ _jsx(motion.p, {
                      style: {
                        "--font-selector": "R0Y7RE0gU2Fucy01MDA=",
                        "--framer-font-family":
                          '"DM Sans", "DM Sans Placeholder", sans-serif',
                        "--framer-font-weight": "500",
                        "--framer-line-height": "1.3em",
                        "--framer-text-color":
                          "var(--extracted-r6o4lv, rgba(53, 48, 44, 0.75))",
                      },
                      children:
                        "You can cancel your plan whenever you’d like. You’ll be downgraded to the free plan. You won’t be locked out of any projects that have paid plans.",
                    }),
                  }),
                  className: "framer-1trzhek",
                  fonts: ["GF;DM Sans-500"],
                  layoutDependency: layoutDependency,
                  layoutId: "jfy8b9_WV",
                  style: {
                    "--extracted-r6o4lv": "rgba(53, 48, 44, 0.75)",
                    "--framer-link-text-color": "rgb(0, 153, 255)",
                    "--framer-link-text-decoration": "underline",
                  },
                  text: m1wBZJAoM,
                  verticalAlignment: "top",
                  withExternalLayout: true,
                }),
              }),
            /*#__PURE__*/ _jsx(motion.div, {
              className: "framer-5lxm8",
              "data-framer-name": "Line Bottom",
              layoutDependency: layoutDependency,
              layoutId: "OCyTFLz5y",
              style: { backgroundColor: "rgba(53, 48, 44, 0.1)", opacity: 0.7 },
            }),
          ],
        }),
      }),
    }),
  });
});
const css = [
  ".framer-1vWZc.framer-wjzrim, .framer-1vWZc .framer-wjzrim { display: block; }",
  ".framer-1vWZc.framer-1xg346n { align-content: flex-start; align-items: flex-start; cursor: pointer; display: flex; flex-direction: column; flex-wrap: nowrap; gap: 16px; height: min-content; justify-content: flex-start; overflow: visible; padding: 0px; position: relative; width: 617px; }",
  ".framer-1vWZc .framer-17kwd86 { align-content: center; align-items: center; display: flex; flex: none; flex-direction: row; flex-wrap: nowrap; height: min-content; justify-content: space-between; overflow: visible; padding: 0px; position: relative; width: 100%; }",
  ".framer-1vWZc .framer-3vzzdf, .framer-1vWZc .framer-1trzhek { flex: 1 0 0px; height: auto; max-width: 90%; overflow: hidden; position: relative; white-space: pre-wrap; width: 1px; word-break: break-word; word-wrap: break-word; }",
  ".framer-1vWZc .framer-170zmkp-container { flex: none; height: auto; position: relative; width: auto; }",
  ".framer-1vWZc .framer-1qn57zt { align-content: center; align-items: center; display: flex; flex: none; flex-direction: row; flex-wrap: nowrap; gap: 10px; height: min-content; justify-content: flex-start; overflow: visible; padding: 0px 40px 0px 0px; position: relative; width: 100%; }",
  ".framer-1vWZc .framer-5lxm8 { flex: none; height: 1px; overflow: hidden; position: relative; width: 100%; }",
  ".framer-1vWZc.framer-v-2jeths.framer-1xg346n { gap: 24px; }",
  ".framer-1vWZc.framer-v-1gc2b9s.framer-1xg346n, .framer-1vWZc.framer-v-3hmb5m.framer-1xg346n { width: 390px; }",
  ".framer-1vWZc.framer-v-1gc2b9s .framer-17kwd86, .framer-1vWZc.framer-v-3hmb5m .framer-17kwd86 { align-content: flex-start; align-items: flex-start; }",
  ".framer-1vWZc.framer-v-1gc2b9s .framer-1qn57zt { padding: 0px 16px 0px 0px; }",
];
/**
 * This is a generated Framer component.
 * @framerIntrinsicHeight 129
 * @framerIntrinsicWidth 617
 * @framerCanvasComponentVariantDetails {"propertyName":"variant","data":{"default":{"layout":["fixed","auto"]},"CwvHPtV1t":{"layout":["fixed","auto"]},"jhF3fI41X":{"layout":["fixed","auto"]},"atF16Hnec":{"layout":["fixed","auto"]},"WmQkLiVEQ":{"layout":["fixed","auto"]}}}
 * @framerVariables {"vd59XDbg4":"question","m1wBZJAoM":"answer"}
 * @framerImmutableVariables true
 * @framerDisplayContentsDiv false
 * @framerAutoSizeImages true
 * @framerComponentViewportWidth true
 * @framerColorSyntax true
 */ const FramerkQIC9ukuG = withCSS(Component, css, "framer-1vWZc");
export default FramerkQIC9ukuG;
FramerkQIC9ukuG.displayName = "FAQ Item";
FramerkQIC9ukuG.defaultProps = { height: 129, width: 617 };
addPropertyControls(FramerkQIC9ukuG, {
  variant: {
    options: ["Is_0zeX5t", "CwvHPtV1t", "jhF3fI41X", "atF16Hnec"],
    optionTitles: ["Open", "Closed", "FAQMobileOpen", "FAQMobileClosed"],
    title: "Variant",
    type: ControlType.Enum,
  },
  vd59XDbg4: {
    defaultValue: "Which pricing plan is right for me?",
    displayTextArea: true,
    title: "Question",
    type: ControlType.String,
  },
  onvd59XDbg4Change: { changes: "vd59XDbg4", type: ControlType.ChangeHandler },
  m1wBZJAoM: {
    defaultValue:
      "You can cancel your plan whenever you’d like. You’ll be downgraded to the free plan. You won’t be locked out of any projects that have paid plans.",
    displayTextArea: true,
    title: "Answer",
    type: ControlType.String,
  },
  onm1wBZJAoMChange: { changes: "m1wBZJAoM", type: ControlType.ChangeHandler },
});
addFonts(
  FramerkQIC9ukuG,
  [
    {
      explicitInter: true,
      fonts: [
        {
          cssFamilyName: "DM Sans",
          source: "google",
          style: "normal",
          uiFamilyName: "DM Sans",
          url: "https://fonts.gstatic.com/s/dmsans/v17/rP2tp2ywxg089UriI5-g4vlH9VoD8CmcqZG40F9JadbnoEwAfJthS2f3ZGMZpg.woff2",
          weight: "600",
        },
        {
          cssFamilyName: "DM Sans",
          source: "google",
          style: "normal",
          uiFamilyName: "DM Sans",
          url: "https://fonts.gstatic.com/s/dmsans/v17/rP2tp2ywxg089UriI5-g4vlH9VoD8CmcqZG40F9JadbnoEwAkJxhS2f3ZGMZpg.woff2",
          weight: "500",
        },
      ],
    },
    ...PlusIconFonts,
  ],
  { supportsExplicitInterCodegen: true }
);
FramerkQIC9ukuG.loader = {
  load: (props, context) => {
    return runTasksWithYield(
      [() => forwardLoader(PlusIcon, {}, context)],
      context
    );
  },
};
export const __FramerMetadata__ = {
  exports: {
    Props: { type: "tsType", annotations: { framerContractVersion: "1" } },
    default: {
      type: "reactComponent",
      name: "FramerkQIC9ukuG",
      slots: [],
      annotations: {
        framerDisplayContentsDiv: "false",
        framerAutoSizeImages: "true",
        framerColorSyntax: "true",
        framerComponentViewportWidth: "true",
        framerCanvasComponentVariantDetails:
          '{"propertyName":"variant","data":{"default":{"layout":["fixed","auto"]},"CwvHPtV1t":{"layout":["fixed","auto"]},"jhF3fI41X":{"layout":["fixed","auto"]},"atF16Hnec":{"layout":["fixed","auto"]},"WmQkLiVEQ":{"layout":["fixed","auto"]}}}',
        framerContractVersion: "1",
        framerIntrinsicWidth: "617",
        framerVariables: '{"vd59XDbg4":"question","m1wBZJAoM":"answer"}',
        framerIntrinsicHeight: "129",
        framerImmutableVariables: "true",
      },
    },
    __FramerMetadata__: { type: "variable" },
  },
};
//# sourceMappingURL=./kQIC9ukuG.map
