// Generated by Framer (fe01371)
import { fontStore } from "framer";
fontStore.loadFonts([
  "GF;DM Sans-600",
  "GF;DM Sans-900",
  "GF;DM Sans-900italic",
  "GF;DM Sans-600italic",
]);
export const fonts = [
  {
    explicitInter: true,
    fonts: [
      {
        cssFamilyName: "DM Sans",
        openType: true,
        source: "google",
        style: "normal",
        uiFamilyName: "DM Sans",
        url: "https://fonts.gstatic.com/s/dmsans/v17/rP2tp2ywxg089UriI5-g4vlH9VoD8CmcqZG40F9JadbnoEwAfJthS2f3ZGMZpg.woff2",
        weight: "600",
      },
      {
        cssFamilyName: "DM Sans",
        openType: true,
        source: "google",
        style: "normal",
        uiFamilyName: "DM Sans",
        url: "https://fonts.gstatic.com/s/dmsans/v17/rP2tp2ywxg089UriI5-g4vlH9VoD8CmcqZG40F9JadbnoEwAC5thS2f3ZGMZpg.woff2",
        weight: "900",
      },
      {
        cssFamilyName: "DM Sans",
        openType: true,
        source: "google",
        style: "italic",
        uiFamilyName: "DM Sans",
        url: "https://fonts.gstatic.com/s/dmsans/v17/rP2rp2ywxg089UriCZaSExd86J3t9jz86Mvy4qCRAL19DksVat8gCm32RmYJpso5.woff2",
        weight: "900",
      },
      {
        cssFamilyName: "DM Sans",
        openType: true,
        source: "google",
        style: "italic",
        uiFamilyName: "DM Sans",
        url: "https://fonts.gstatic.com/s/dmsans/v17/rP2rp2ywxg089UriCZaSExd86J3t9jz86Mvy4qCRAL19DksVat9XCm32RmYJpso5.woff2",
        weight: "600",
      },
    ],
  },
];
export const css = [
  '.framer-21hKb .framer-styles-preset-4r7lxl:not(.rich-text-wrapper), .framer-21hKb .framer-styles-preset-4r7lxl.rich-text-wrapper h3 { --framer-font-family: "DM Sans", "DM Sans Placeholder", sans-serif; --framer-font-family-bold: "DM Sans", sans-serif; --framer-font-family-bold-italic: "DM Sans", sans-serif; --framer-font-family-italic: "DM Sans", "DM Sans Placeholder", sans-serif; --framer-font-open-type-features: \'blwf\' on, \'cv09\' on, \'cv03\' on, \'cv04\' on, \'cv11\' on; --framer-font-size: 20px; --framer-font-style: normal; --framer-font-style-bold: normal; --framer-font-style-bold-italic: italic; --framer-font-style-italic: italic; --framer-font-variation-axes: normal; --framer-font-weight: 600; --framer-font-weight-bold: 900; --framer-font-weight-bold-italic: 900; --framer-font-weight-italic: 600; --framer-letter-spacing: -0.03em; --framer-line-height: 1.2em; --framer-paragraph-spacing: 40px; --framer-text-alignment: start; --framer-text-color: var(--token-1d17d240-c237-41bb-a020-01ece6e53ba1, #262335); --framer-text-decoration: none; --framer-text-stroke-color: initial; --framer-text-stroke-width: initial; --framer-text-transform: none; }',
];
export const className = "framer-21hKb";
export const __FramerMetadata__ = {
  exports: {
    className: {
      type: "variable",
      annotations: { framerContractVersion: "1" },
    },
    fonts: { type: "variable", annotations: { framerContractVersion: "1" } },
    css: { type: "variable", annotations: { framerContractVersion: "1" } },
    __FramerMetadata__: { type: "variable" },
  },
};
