// Generated by Framer (0b0b0ac)
import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import {
  addFonts,
  addPropertyControls,
  ComponentViewportProvider,
  ControlType,
  cx,
  forwardLoader,
  getFonts,
  Link,
  RichText,
  SmartComponentScopedContainer,
  SVG,
  useActiveVariantCallback,
  useComponentViewport,
  useLocaleInfo,
  useVariantState,
  withCSS,
} from "framer";
import { LayoutGroup, motion, MotionConfigContext } from "framer-motion";
import * as React from "react";
import { useRef } from "react";
import Menu from "https://framerusercontent.com/modules/w9r3BVDBgmWy7W7xOeUc/qECxFwcsABn3SUQ7vp5x/rRJRVI52H.js";
import DownloadButton from "https://framerusercontent.com/modules/1A6yp1k7iDdOH1OS5ko5/HZ0dfuwqLBjegQpueUET/B8aAPWvMX.js";
const MenuFonts = getFonts(Menu);
const DownloadButtonFonts = getFonts(DownloadButton);
const cycleOrder = ["KseaieyoG", "tCDt2iF8Z", "zPJ3g9Bac", "YNJh_zUwK"];
const serializationHash = "framer-cs6CW";
const variantClassNames = {
  KseaieyoG: "framer-v-j4bbtl",
  tCDt2iF8Z: "framer-v-1y1p2eb",
  YNJh_zUwK: "framer-v-1kenqkc",
  zPJ3g9Bac: "framer-v-1epkyf9",
};
function addPropertyOverrides(overrides, ...variants) {
  const nextOverrides = {};
  variants?.forEach(
    (variant) => variant && Object.assign(nextOverrides, overrides[variant])
  );
  return nextOverrides;
}
const transition1 = { bounce: 0.2, delay: 0, duration: 0.4, type: "spring" };
const transition2 = {
  delay: 0,
  duration: 0.4,
  ease: [0.44, 0, 0.56, 1],
  type: "tween",
};
const transformTemplate1 = (_, t) => `translateY(-50%) ${t}`;
const matchVariant = (...args) => {
  for (const arg of args) {
    if (arg && typeof arg === "string") return arg;
  }
  return undefined;
};
const Transition = ({ value, children }) => {
  const config = React.useContext(MotionConfigContext);
  const transition = value ?? config.transition;
  const contextValue = React.useMemo(
    () => ({ ...config, transition }),
    [JSON.stringify(transition)]
  );
  return /*#__PURE__*/ _jsx(MotionConfigContext.Provider, {
    value: contextValue,
    children: children,
  });
};
const humanReadableVariantMap = {
  "Variant 4": "YNJh_zUwK",
  Desktop: "KseaieyoG",
  Phone: "zPJ3g9Bac",
  Tablet: "tCDt2iF8Z",
};
const Variants = motion.create(React.Fragment);
const getProps = ({ height, id, width, ...props }) => {
  return {
    ...props,
    variant:
      humanReadableVariantMap[props.variant] ?? props.variant ?? "KseaieyoG",
  };
};
const createLayoutDependency = (props, variants) => {
  if (props.layoutDependency)
    return variants.join("-") + props.layoutDependency;
  return variants.join("-");
};
const Component = /*#__PURE__*/ React.forwardRef(function (props, ref) {
  const fallbackRef = useRef(null);
  const refBinding = ref ?? fallbackRef;
  const defaultLayoutId = React.useId();
  const { activeLocale, setLocale } = useLocaleInfo();
  const componentViewport = useComponentViewport();
  const { style, className, layoutId, variant, ...restProps } = getProps(props);
  const {
    baseVariant,
    classNames,
    clearLoadingGesture,
    gestureHandlers,
    gestureVariant,
    isLoading,
    setGestureState,
    setVariant,
    variants,
  } = useVariantState({
    cycleOrder,
    defaultVariant: "KseaieyoG",
    ref: refBinding,
    variant,
    variantClassNames,
  });
  const layoutDependency = createLayoutDependency(props, variants);
  const { activeVariantCallback, delay } =
    useActiveVariantCallback(baseVariant);
  const onTapnirc4z = activeVariantCallback(async (...args) => {
    setVariant("zPJ3g9Bac");
  });
  const onTap1o1fh4y = activeVariantCallback(async (...args) => {
    setVariant("YNJh_zUwK");
  });
  const sharedStyleClassNames = [];
  const scopingClassNames = cx(serializationHash, ...sharedStyleClassNames);
  const isDisplayed = () => {
    if (baseVariant === "zPJ3g9Bac") return false;
    return true;
  };
  const isDisplayed1 = () => {
    if (baseVariant === "YNJh_zUwK") return false;
    return true;
  };
  const isDisplayed2 = () => {
    if (baseVariant === "YNJh_zUwK") return true;
    return false;
  };
  const isDisplayed3 = () => {
    if (baseVariant === "zPJ3g9Bac") return true;
    return false;
  };
  return /*#__PURE__*/ _jsx(LayoutGroup, {
    id: layoutId ?? defaultLayoutId,
    children: /*#__PURE__*/ _jsx(Variants, {
      animate: variants,
      initial: false,
      children: /*#__PURE__*/ _jsx(Transition, {
        value: transition1,
        ...addPropertyOverrides(
          {
            YNJh_zUwK: { value: transition2 },
            zPJ3g9Bac: { value: transition2 },
          },
          baseVariant,
          gestureVariant
        ),
        children: /*#__PURE__*/ _jsxs(motion.div, {
          ...restProps,
          ...gestureHandlers,
          className: cx(
            scopingClassNames,
            "framer-j4bbtl",
            className,
            classNames
          ),
          "data-border": true,
          "data-framer-name": "Desktop",
          layoutDependency: layoutDependency,
          layoutId: "KseaieyoG",
          ref: refBinding,
          style: {
            "--border-bottom-width": "1px",
            "--border-color": "rgba(255, 255, 255, 0.5)",
            "--border-left-width": "0px",
            "--border-right-width": "0px",
            "--border-style": "solid",
            "--border-top-width": "0px",
            backdropFilter: "blur(6px)",
            backgroundColor: "rgba(255, 255, 255, 0.25)",
            WebkitBackdropFilter: "blur(6px)",
            ...style,
          },
          ...addPropertyOverrides(
            {
              tCDt2iF8Z: { "data-framer-name": "Tablet" },
              YNJh_zUwK: { "data-framer-name": "Variant 4" },
              zPJ3g9Bac: { "data-framer-name": "Phone" },
            },
            baseVariant,
            gestureVariant
          ),
          children: [
            isDisplayed() &&
              /*#__PURE__*/ _jsx(motion.div, {
                className: "framer-ct2iwj",
                layoutDependency: layoutDependency,
                layoutId: "bBy1Io9r3",
                transformTemplate: transformTemplate1,
                ...addPropertyOverrides(
                  { YNJh_zUwK: { transformTemplate: undefined } },
                  baseVariant,
                  gestureVariant
                ),
                children:
                  isDisplayed1() &&
                  /*#__PURE__*/ _jsx(Link, {
                    href: { webPageId: "augiA20Il" },
                    motionChild: true,
                    nodeId: "g9PSRvboU",
                    openInNewTab: false,
                    scopeId: "huAklyris",
                    children: /*#__PURE__*/ _jsx(motion.a, {
                      className: "framer-1y7gnqw framer-1dk4bf7",
                      layoutDependency: layoutDependency,
                      layoutId: "g9PSRvboU",
                      children: /*#__PURE__*/ _jsxs(SVG, {
                        className: "framer-68xt2m",
                        layoutDependency: layoutDependency,
                        layoutId: "zEExVcC24",
                        requiresOverflowVisible: false,
                        svg: '<svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" viewBox="0 0 63.335 29.52" overflow="visible"><path d="M 0 28.782 C 1.292 27.97 2.362 26.789 3.174 24.538 L 10.885 3.469 C 11.217 2.51 11.217 1.699 10.959 0.96 L 15.793 0.96 L 24.723 24.723 C 25.46 26.715 26.235 27.97 27.49 28.745 L 27.49 28.892 L 18.708 28.892 L 18.708 28.782 C 20.184 27.97 20.294 26.752 19.593 24.76 L 18.117 20.48 L 7.417 20.48 L 5.977 24.649 C 5.24 26.863 5.314 28.007 6.605 28.782 L 6.605 28.892 L 0 28.892 Z M 8.155 18.413 L 17.416 18.413 L 12.805 4.983 L 8.154 18.413 Z M 35.035 29.52 C 29.869 29.52 26.512 27.01 25.995 22.915 L 29.943 22.915 C 30.275 25.867 31.973 27.638 35.072 27.638 C 37.212 27.638 38.762 26.752 38.762 25.055 C 38.762 23.173 37.212 22.583 33.448 21.217 C 29.98 19.963 26.954 18.708 26.954 15.314 C 26.954 12.104 29.98 10.148 34.297 10.148 C 38.836 10.148 41.787 12.214 42.489 15.683 L 38.614 15.683 C 38.319 13.506 36.917 12.03 34.186 12.03 C 32.157 12.03 30.866 12.878 30.866 14.354 C 30.866 16.236 32.71 17.011 36.106 18.192 C 40.053 19.557 42.71 20.885 42.71 24.132 C 42.71 27.749 39.352 29.52 35.035 29.52 Z M 43.115 28.892 L 43.115 28.745 C 44.442 27.822 44.664 26.457 44.664 23.764 L 44.664 5.203 C 44.664 2.989 44.405 1.734 43.299 0.812 L 43.299 0.701 L 49.239 0 L 49.276 0.147 C 49.092 1.254 49.018 2.214 49.018 5.203 L 49.018 14.833 C 50.162 12.213 52.523 10.147 55.992 10.147 C 59.608 10.147 61.895 12.139 61.895 17.194 L 61.895 23.763 C 61.895 26.456 62.08 27.821 63.335 28.743 L 63.335 28.891 L 56.175 28.891 L 56.175 28.744 C 57.319 27.821 57.504 26.456 57.504 23.763 L 57.504 17.343 C 57.504 14.095 56.323 12.73 53.998 12.73 C 51.378 12.73 49.608 14.76 49.017 17.268 L 49.017 23.763 C 49.017 26.456 49.238 27.821 50.53 28.743 L 50.53 28.891 L 43.113 28.891 Z" fill="rgb(111,108,84)"></path></svg>',
                        withExternalLayout: true,
                        children: [
                          /*#__PURE__*/ _jsx(SVG, {
                            className: "framer-vo03of",
                            layoutDependency: layoutDependency,
                            layoutId: "op5mvKXn0",
                            requiresOverflowVisible: false,
                            svg: '<svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" viewBox="0 0 27.49 27.932" overflow="visible"><path d="M 0 27.822 C 1.292 27.01 2.362 25.829 3.174 23.578 L 10.885 2.509 C 11.217 1.55 11.217 0.739 10.959 0 L 15.793 0 L 24.723 23.763 C 25.46 25.755 26.235 27.01 27.49 27.785 L 27.49 27.932 L 18.708 27.932 L 18.708 27.822 C 20.184 27.01 20.294 25.792 19.593 23.8 L 18.117 19.52 L 7.417 19.52 L 5.977 23.689 C 5.24 25.903 5.314 27.047 6.605 27.822 L 6.605 27.932 L 0 27.932 Z" fill="transparent"></path></svg>',
                            withExternalLayout: true,
                          }),
                          /*#__PURE__*/ _jsx(SVG, {
                            className: "framer-wi15qr",
                            layoutDependency: layoutDependency,
                            layoutId: "T4tkDktp5",
                            requiresOverflowVisible: false,
                            svg: '<svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" viewBox="0 0 9.262 13.43" overflow="visible"><path d="M 0.001 13.43 L 9.262 13.43 L 4.651 0 L 0 13.43 Z" fill="transparent"></path></svg>',
                            withExternalLayout: true,
                          }),
                          /*#__PURE__*/ _jsx(SVG, {
                            className: "framer-1o9gake",
                            layoutDependency: layoutDependency,
                            layoutId: "OKE1Su_8Y",
                            requiresOverflowVisible: false,
                            svg: '<svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" viewBox="0 0 16.715 19.372" overflow="visible"><path d="M 9.04 19.372 C 3.874 19.372 0.517 16.862 0 12.767 L 3.948 12.767 C 4.28 15.719 5.978 17.49 9.077 17.49 C 11.217 17.49 12.767 16.604 12.767 14.907 C 12.767 13.025 11.217 12.435 7.453 11.069 C 3.985 9.815 0.959 8.56 0.959 5.166 C 0.959 1.956 3.985 0 8.302 0 C 12.841 0 15.792 2.066 16.494 5.535 L 12.619 5.535 C 12.324 3.358 10.922 1.882 8.191 1.882 C 6.162 1.882 4.871 2.73 4.871 4.206 C 4.871 6.088 6.715 6.863 10.111 8.044 C 14.058 9.409 16.715 10.737 16.715 13.984 C 16.715 17.601 13.357 19.372 9.04 19.372 Z" fill="transparent"></path></svg>',
                            withExternalLayout: true,
                          }),
                          /*#__PURE__*/ _jsx(SVG, {
                            className: "framer-5jb52q",
                            layoutDependency: layoutDependency,
                            layoutId: "wMRSE5Lyu",
                            requiresOverflowVisible: false,
                            svg: '<svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" viewBox="0 0 20.222 28.892" overflow="visible"><path d="M 0.002 28.892 L 0.002 28.745 C 1.329 27.822 1.551 26.457 1.551 23.764 L 1.551 5.203 C 1.551 2.989 1.292 1.734 0.186 0.812 L 0.186 0.701 L 6.126 0 L 6.163 0.147 C 5.979 1.254 5.905 2.214 5.905 5.203 L 5.905 14.833 C 7.049 12.213 9.41 10.147 12.879 10.147 C 16.495 10.147 18.782 12.139 18.782 17.194 L 18.782 23.763 C 18.782 26.456 18.967 27.821 20.222 28.743 L 20.222 28.891 L 13.062 28.891 L 13.062 28.744 C 14.206 27.821 14.391 26.456 14.391 23.763 L 14.391 17.343 C 14.391 14.095 13.21 12.73 10.885 12.73 C 8.265 12.73 6.495 14.76 5.904 17.268 L 5.904 23.763 C 5.904 26.456 6.125 27.821 7.417 28.743 L 7.417 28.891 L 0 28.891 Z" fill="transparent"></path></svg>',
                            withExternalLayout: true,
                          }),
                        ],
                      }),
                    }),
                  }),
              }),
            isDisplayed() &&
              /*#__PURE__*/ _jsx(Link, {
                href: { webPageId: "augiA20Il" },
                motionChild: true,
                nodeId: "L4LB7gLrQ",
                openInNewTab: false,
                scopeId: "huAklyris",
                children: /*#__PURE__*/ _jsx(motion.a, {
                  className: "framer-2se6oy framer-1dk4bf7",
                  layoutDependency: layoutDependency,
                  layoutId: "L4LB7gLrQ",
                  children: /*#__PURE__*/ _jsx(RichText, {
                    __fromCanvasComponent: true,
                    children: /*#__PURE__*/ _jsx(React.Fragment, {
                      children: /*#__PURE__*/ _jsx(motion.p, {
                        style: {
                          "--font-selector": "R0Y7RE0gU2Fucy02MDA=",
                          "--framer-font-family":
                            '"DM Sans", "DM Sans Placeholder", sans-serif',
                          "--framer-font-weight": "600",
                          "--framer-line-height": "150%",
                          "--framer-text-color":
                            "var(--extracted-r6o4lv, var(--token-0ecaa262-9aac-4113-a5a5-5bfcb0d17214, rgb(53, 48, 43)))",
                        },
                        children: "Home",
                      }),
                    }),
                    className: "framer-f536yv",
                    fonts: ["GF;DM Sans-600"],
                    layoutDependency: layoutDependency,
                    layoutId: "VaVHuGzxu",
                    style: {
                      "--extracted-r6o4lv":
                        "var(--token-0ecaa262-9aac-4113-a5a5-5bfcb0d17214, rgb(53, 48, 43))",
                      "--framer-link-text-color": "rgb(0, 153, 255)",
                      "--framer-link-text-decoration": "underline",
                    },
                    verticalAlignment: "top",
                    withExternalLayout: true,
                    ...addPropertyOverrides(
                      {
                        YNJh_zUwK: {
                          children: /*#__PURE__*/ _jsx(React.Fragment, {
                            children: /*#__PURE__*/ _jsx(motion.p, {
                              style: {
                                "--font-selector": "R0Y7RE0gU2Fucy02MDA=",
                                "--framer-font-family":
                                  '"DM Sans", "DM Sans Placeholder", sans-serif',
                                "--framer-font-size": "20px",
                                "--framer-font-weight": "600",
                                "--framer-letter-spacing": "-0.04em",
                                "--framer-line-height": "150%",
                                "--framer-text-color":
                                  "var(--extracted-r6o4lv, var(--token-0ecaa262-9aac-4113-a5a5-5bfcb0d17214, rgb(53, 48, 43)))",
                              },
                              children: "Home",
                            }),
                          }),
                        },
                      },
                      baseVariant,
                      gestureVariant
                    ),
                  }),
                }),
              }),
            isDisplayed() &&
              /*#__PURE__*/ _jsx(Link, {
                href: { webPageId: "ZWKB3Jdq7" },
                motionChild: true,
                nodeId: "lRWDRpAPi",
                openInNewTab: false,
                scopeId: "huAklyris",
                children: /*#__PURE__*/ _jsx(motion.a, {
                  className: "framer-1dvmw63 framer-1dk4bf7",
                  layoutDependency: layoutDependency,
                  layoutId: "lRWDRpAPi",
                  children: /*#__PURE__*/ _jsx(RichText, {
                    __fromCanvasComponent: true,
                    children: /*#__PURE__*/ _jsx(React.Fragment, {
                      children: /*#__PURE__*/ _jsx(motion.p, {
                        style: {
                          "--font-selector": "R0Y7RE0gU2Fucy02MDA=",
                          "--framer-font-family":
                            '"DM Sans", "DM Sans Placeholder", sans-serif',
                          "--framer-font-weight": "600",
                          "--framer-line-height": "150%",
                          "--framer-text-color":
                            "var(--extracted-r6o4lv, var(--token-0ecaa262-9aac-4113-a5a5-5bfcb0d17214, rgb(53, 48, 43)))",
                        },
                        children: "About Us",
                      }),
                    }),
                    className: "framer-12qx7xn",
                    fonts: ["GF;DM Sans-600"],
                    layoutDependency: layoutDependency,
                    layoutId: "jnGDRFuh7",
                    style: {
                      "--extracted-r6o4lv":
                        "var(--token-0ecaa262-9aac-4113-a5a5-5bfcb0d17214, rgb(53, 48, 43))",
                      "--framer-link-text-color": "rgb(0, 153, 255)",
                      "--framer-link-text-decoration": "underline",
                    },
                    verticalAlignment: "top",
                    withExternalLayout: true,
                    ...addPropertyOverrides(
                      {
                        YNJh_zUwK: {
                          children: /*#__PURE__*/ _jsx(React.Fragment, {
                            children: /*#__PURE__*/ _jsx(motion.p, {
                              style: {
                                "--font-selector": "R0Y7RE0gU2Fucy02MDA=",
                                "--framer-font-family":
                                  '"DM Sans", "DM Sans Placeholder", sans-serif',
                                "--framer-font-size": "20px",
                                "--framer-font-weight": "600",
                                "--framer-letter-spacing": "-0.04em",
                                "--framer-line-height": "150%",
                                "--framer-text-color":
                                  "var(--extracted-r6o4lv, var(--token-0ecaa262-9aac-4113-a5a5-5bfcb0d17214, rgb(53, 48, 43)))",
                              },
                              children: "About Us",
                            }),
                          }),
                        },
                      },
                      baseVariant,
                      gestureVariant
                    ),
                  }),
                }),
              }),
            isDisplayed2() &&
              /*#__PURE__*/ _jsx(motion.div, {
                className: "framer-syls8j",
                "data-highlight": true,
                layoutDependency: layoutDependency,
                layoutId: "nEI3Vdtie",
                onTap: onTapnirc4z,
                children: /*#__PURE__*/ _jsx(Menu, {
                  animated: true,
                  className: "framer-a68hwj",
                  layoutDependency: layoutDependency,
                  layoutId: "L7rZmoUmB",
                  style: {
                    "--43q7um":
                      "var(--token-0ecaa262-9aac-4113-a5a5-5bfcb0d17214, rgb(53, 48, 43))",
                  },
                }),
              }),
            isDisplayed3() &&
              /*#__PURE__*/ _jsx(motion.div, {
                className: "framer-16byl75",
                "data-highlight": true,
                layoutDependency: layoutDependency,
                layoutId: "pS46tshvG",
                onTap: onTap1o1fh4y,
                children: /*#__PURE__*/ _jsx(Menu, {
                  animated: true,
                  className: "framer-4pb7zn",
                  layoutDependency: layoutDependency,
                  layoutId: "yGudOVjqJ",
                  style: {
                    "--43q7um":
                      "var(--token-0ecaa262-9aac-4113-a5a5-5bfcb0d17214, rgb(53, 48, 43))",
                  },
                }),
              }),
            isDisplayed() &&
              /*#__PURE__*/ _jsx(Link, {
                href: { webPageId: "N_9TcloSF" },
                motionChild: true,
                nodeId: "FQuUHtumS",
                openInNewTab: false,
                scopeId: "huAklyris",
                children: /*#__PURE__*/ _jsx(motion.a, {
                  className: "framer-125g5ag framer-1dk4bf7",
                  layoutDependency: layoutDependency,
                  layoutId: "FQuUHtumS",
                  children: /*#__PURE__*/ _jsx(RichText, {
                    __fromCanvasComponent: true,
                    children: /*#__PURE__*/ _jsx(React.Fragment, {
                      children: /*#__PURE__*/ _jsx(motion.p, {
                        dir: "auto",
                        style: {
                          "--font-selector": "R0Y7RE0gU2Fucy02MDA=",
                          "--framer-font-family":
                            '"DM Sans", "DM Sans Placeholder", sans-serif',
                          "--framer-font-weight": "600",
                          "--framer-line-height": "150%",
                          "--framer-text-color":
                            "var(--extracted-r6o4lv, var(--token-0ecaa262-9aac-4113-a5a5-5bfcb0d17214, rgb(53, 48, 43)))",
                        },
                        children: "Blog",
                      }),
                    }),
                    className: "framer-19g0ag7",
                    fonts: ["GF;DM Sans-600"],
                    layoutDependency: layoutDependency,
                    layoutId: "YNlni8MG7",
                    style: {
                      "--extracted-r6o4lv":
                        "var(--token-0ecaa262-9aac-4113-a5a5-5bfcb0d17214, rgb(53, 48, 43))",
                      "--framer-link-text-color": "rgb(0, 153, 255)",
                      "--framer-link-text-decoration": "underline",
                    },
                    verticalAlignment: "top",
                    withExternalLayout: true,
                    ...addPropertyOverrides(
                      {
                        YNJh_zUwK: {
                          children: /*#__PURE__*/ _jsx(React.Fragment, {
                            children: /*#__PURE__*/ _jsx(motion.p, {
                              dir: "auto",
                              style: {
                                "--font-selector": "R0Y7RE0gU2Fucy02MDA=",
                                "--framer-font-family":
                                  '"DM Sans", "DM Sans Placeholder", sans-serif',
                                "--framer-font-size": "20px",
                                "--framer-font-weight": "600",
                                "--framer-letter-spacing": "-0.04em",
                                "--framer-line-height": "150%",
                                "--framer-text-color":
                                  "var(--extracted-r6o4lv, var(--token-0ecaa262-9aac-4113-a5a5-5bfcb0d17214, rgb(53, 48, 43)))",
                              },
                              children: "Blog",
                            }),
                          }),
                        },
                      },
                      baseVariant,
                      gestureVariant
                    ),
                  }),
                }),
              }),
            isDisplayed() &&
              /*#__PURE__*/ _jsx(Link, {
                href: { webPageId: "eLg12ESky" },
                motionChild: true,
                nodeId: "qSUBKybp3",
                openInNewTab: false,
                scopeId: "huAklyris",
                children: /*#__PURE__*/ _jsx(motion.a, {
                  className: "framer-2lx0pm framer-1dk4bf7",
                  layoutDependency: layoutDependency,
                  layoutId: "qSUBKybp3",
                  children: /*#__PURE__*/ _jsx(RichText, {
                    __fromCanvasComponent: true,
                    children: /*#__PURE__*/ _jsx(React.Fragment, {
                      children: /*#__PURE__*/ _jsx(motion.p, {
                        dir: "auto",
                        style: {
                          "--font-selector": "R0Y7RE0gU2Fucy02MDA=",
                          "--framer-font-family":
                            '"DM Sans", "DM Sans Placeholder", sans-serif',
                          "--framer-font-weight": "600",
                          "--framer-line-height": "150%",
                          "--framer-text-color":
                            "var(--extracted-r6o4lv, var(--token-0ecaa262-9aac-4113-a5a5-5bfcb0d17214, rgb(53, 48, 43)))",
                        },
                        children: "Research",
                      }),
                    }),
                    className: "framer-1qsc6y9",
                    fonts: ["GF;DM Sans-600"],
                    layoutDependency: layoutDependency,
                    layoutId: "INOWUs9nW",
                    style: {
                      "--extracted-r6o4lv":
                        "var(--token-0ecaa262-9aac-4113-a5a5-5bfcb0d17214, rgb(53, 48, 43))",
                      "--framer-link-text-color": "rgb(0, 153, 255)",
                      "--framer-link-text-decoration": "underline",
                    },
                    verticalAlignment: "top",
                    withExternalLayout: true,
                    ...addPropertyOverrides(
                      {
                        YNJh_zUwK: {
                          children: /*#__PURE__*/ _jsx(React.Fragment, {
                            children: /*#__PURE__*/ _jsx(motion.p, {
                              dir: "auto",
                              style: {
                                "--font-selector": "R0Y7RE0gU2Fucy02MDA=",
                                "--framer-font-family":
                                  '"DM Sans", "DM Sans Placeholder", sans-serif',
                                "--framer-font-size": "20px",
                                "--framer-font-weight": "600",
                                "--framer-letter-spacing": "-0.04em",
                                "--framer-line-height": "150%",
                                "--framer-text-color":
                                  "var(--extracted-r6o4lv, var(--token-0ecaa262-9aac-4113-a5a5-5bfcb0d17214, rgb(53, 48, 43)))",
                              },
                              children: "Research",
                            }),
                          }),
                        },
                      },
                      baseVariant,
                      gestureVariant
                    ),
                  }),
                }),
              }),
            isDisplayed() &&
              /*#__PURE__*/ _jsx(Link, {
                href: { webPageId: "s1cqy0MJT" },
                motionChild: true,
                nodeId: "HhHNKoUct",
                openInNewTab: false,
                scopeId: "huAklyris",
                children: /*#__PURE__*/ _jsx(motion.a, {
                  className: "framer-7qlkm4 framer-1dk4bf7",
                  layoutDependency: layoutDependency,
                  layoutId: "HhHNKoUct",
                  children: /*#__PURE__*/ _jsx(RichText, {
                    __fromCanvasComponent: true,
                    children: /*#__PURE__*/ _jsx(React.Fragment, {
                      children: /*#__PURE__*/ _jsx(motion.p, {
                        dir: "auto",
                        style: {
                          "--font-selector": "R0Y7RE0gU2Fucy02MDA=",
                          "--framer-font-family":
                            '"DM Sans", "DM Sans Placeholder", sans-serif',
                          "--framer-font-weight": "600",
                          "--framer-line-height": "150%",
                          "--framer-text-color":
                            "var(--extracted-r6o4lv, var(--token-0ecaa262-9aac-4113-a5a5-5bfcb0d17214, rgb(53, 48, 43)))",
                        },
                        children: "News",
                      }),
                    }),
                    className: "framer-18c7u49",
                    fonts: ["GF;DM Sans-600"],
                    layoutDependency: layoutDependency,
                    layoutId: "OZPEWNB9P",
                    style: {
                      "--extracted-r6o4lv":
                        "var(--token-0ecaa262-9aac-4113-a5a5-5bfcb0d17214, rgb(53, 48, 43))",
                      "--framer-link-text-color": "rgb(0, 153, 255)",
                      "--framer-link-text-decoration": "underline",
                    },
                    verticalAlignment: "top",
                    withExternalLayout: true,
                    ...addPropertyOverrides(
                      {
                        YNJh_zUwK: {
                          children: /*#__PURE__*/ _jsx(React.Fragment, {
                            children: /*#__PURE__*/ _jsx(motion.p, {
                              dir: "auto",
                              style: {
                                "--font-selector": "R0Y7RE0gU2Fucy02MDA=",
                                "--framer-font-family":
                                  '"DM Sans", "DM Sans Placeholder", sans-serif',
                                "--framer-font-size": "20px",
                                "--framer-font-weight": "600",
                                "--framer-letter-spacing": "-0.04em",
                                "--framer-line-height": "150%",
                                "--framer-text-color":
                                  "var(--extracted-r6o4lv, var(--token-0ecaa262-9aac-4113-a5a5-5bfcb0d17214, rgb(53, 48, 43)))",
                              },
                              children: "News",
                            }),
                          }),
                        },
                      },
                      baseVariant,
                      gestureVariant
                    ),
                  }),
                }),
              }),
            /*#__PURE__*/ _jsx(ComponentViewportProvider, {
              height: 48,
              width: "120px",
              y:
                (componentViewport?.y || 0) +
                ((componentViewport?.height || 64) * 0.5000000000000002 - 24),
              ...addPropertyOverrides(
                {
                  YNJh_zUwK: { height: 40, y: (componentViewport?.y || 0) + 8 },
                  zPJ3g9Bac: {
                    height: 40,
                    y:
                      (componentViewport?.y || 0) +
                      ((componentViewport?.height || 56) * 0.5000000000000002 -
                        20),
                  },
                },
                baseVariant,
                gestureVariant
              ),
              children: /*#__PURE__*/ _jsx(SmartComponentScopedContainer, {
                className: "framer-tug0tr-container",
                layoutDependency: layoutDependency,
                layoutId: "Spahxyyxv-container",
                nodeId: "Spahxyyxv",
                rendersWithMotion: true,
                scopeId: "huAklyris",
                children: /*#__PURE__*/ _jsx(DownloadButton, {
                  etyq7tFCs: "/dashboard",
                  height: "100%",
                  id: "Spahxyyxv",
                  layoutId: "Spahxyyxv",
                  style: { height: "100%", width: "100%" },
                  variant: matchVariant("ftbVpeA1b"),
                  width: "100%",
                  XDhrjNHnD: "Get Started",
                  ...addPropertyOverrides(
                    {
                      YNJh_zUwK: { variant: matchVariant("d2pkkZljh") },
                      zPJ3g9Bac: { variant: matchVariant("d2pkkZljh") },
                    },
                    baseVariant,
                    gestureVariant
                  ),
                }),
              }),
            }),
          ],
        }),
      }),
    }),
  });
});
const css = [
  "@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }",
  ".framer-cs6CW.framer-1dk4bf7, .framer-cs6CW .framer-1dk4bf7 { display: block; }",
  ".framer-cs6CW.framer-j4bbtl { align-content: center; align-items: center; display: flex; flex-direction: row; flex-wrap: nowrap; gap: 0px; height: 64px; justify-content: center; overflow: hidden; padding: 0px; position: relative; width: 1200px; }",
  ".framer-cs6CW .framer-ct2iwj { align-content: flex-end; align-items: flex-end; display: flex; flex: none; flex-direction: row; flex-wrap: nowrap; gap: 16px; height: min-content; justify-content: center; left: 24px; overflow: visible; padding: 0px; position: absolute; top: 50%; width: min-content; z-index: 1; }",
  ".framer-cs6CW .framer-1y7gnqw { align-content: center; align-items: center; display: flex; flex: none; flex-direction: column; flex-wrap: nowrap; gap: 10px; height: min-content; justify-content: center; mix-blend-mode: difference; overflow: visible; padding: 0px; position: relative; text-decoration: none; width: min-content; }",
  ".framer-cs6CW .framer-68xt2m { height: 30px; position: relative; width: 64px; }",
  ".framer-cs6CW .framer-vo03of { height: 28px; left: 0px; position: absolute; top: 1px; width: 28px; }",
  ".framer-cs6CW .framer-wi15qr { height: 14px; left: 8px; position: absolute; top: 5px; width: 10px; }",
  ".framer-cs6CW .framer-1o9gake { height: 20px; left: 26px; position: absolute; top: 10px; width: 17px; }",
  ".framer-cs6CW .framer-5jb52q { height: 29px; left: 43px; position: absolute; top: 0px; width: 20px; }",
  ".framer-cs6CW .framer-2se6oy, .framer-cs6CW .framer-1dvmw63, .framer-cs6CW .framer-125g5ag, .framer-cs6CW .framer-2lx0pm, .framer-cs6CW .framer-7qlkm4 { align-content: center; align-items: center; display: flex; flex: none; flex-direction: row; flex-wrap: nowrap; gap: 10px; height: 40px; justify-content: center; overflow: visible; padding: 0px; position: relative; text-decoration: none; width: 90px; }",
  ".framer-cs6CW .framer-f536yv, .framer-cs6CW .framer-12qx7xn, .framer-cs6CW .framer-19g0ag7, .framer-cs6CW .framer-1qsc6y9, .framer-cs6CW .framer-18c7u49 { flex: none; height: auto; position: relative; white-space: pre; width: auto; }",
  ".framer-cs6CW .framer-syls8j, .framer-cs6CW .framer-16byl75 { align-content: center; align-items: center; cursor: pointer; display: flex; flex: none; flex-direction: row; flex-wrap: nowrap; gap: 10px; height: 40px; justify-content: center; overflow: hidden; padding: 0px; position: relative; width: 40px; }",
  ".framer-cs6CW .framer-a68hwj, .framer-cs6CW .framer-4pb7zn { flex: none; height: var(--framer-aspect-ratio-supported, 24px); position: relative; width: 24px; }",
  ".framer-cs6CW .framer-tug0tr-container { flex: none; height: 48px; position: absolute; right: 24px; top: calc(50.00000000000002% - 48px / 2); width: 120px; z-index: 1; }",
  ".framer-cs6CW.framer-v-1y1p2eb.framer-j4bbtl { width: 810px; }",
  ".framer-cs6CW.framer-v-1epkyf9.framer-j4bbtl { gap: 4px; height: 56px; justify-content: flex-start; padding: 0px 0px 0px 16px; width: 390px; }",
  ".framer-cs6CW.framer-v-1epkyf9 .framer-16byl75, .framer-cs6CW.framer-v-1kenqkc .framer-syls8j { order: 0; }",
  ".framer-cs6CW.framer-v-1epkyf9 .framer-tug0tr-container { height: 40px; order: 8; right: 16px; top: calc(50.00000000000002% - 40px / 2); }",
  ".framer-cs6CW.framer-v-1kenqkc.framer-j4bbtl { align-content: flex-start; align-items: flex-start; flex-direction: column; gap: 8px; height: 1308px; justify-content: flex-start; padding: 8px 0px 0px 16px; width: 390px; }",
  ".framer-cs6CW.framer-v-1kenqkc .framer-ct2iwj { left: unset; min-height: 23px; min-width: 60px; order: 9; position: relative; top: unset; }",
  ".framer-cs6CW.framer-v-1kenqkc .framer-2se6oy { justify-content: flex-start; order: 1; padding: 0px 8px 0px 8px; width: min-content; }",
  ".framer-cs6CW.framer-v-1kenqkc .framer-1dvmw63 { justify-content: flex-start; order: 2; padding: 0px 8px 0px 8px; width: min-content; }",
  ".framer-cs6CW.framer-v-1kenqkc .framer-125g5ag { justify-content: flex-start; order: 5; padding: 0px 8px 0px 8px; width: min-content; }",
  ".framer-cs6CW.framer-v-1kenqkc .framer-2lx0pm { justify-content: flex-start; order: 6; padding: 0px 8px 0px 8px; width: min-content; }",
  ".framer-cs6CW.framer-v-1kenqkc .framer-7qlkm4 { justify-content: flex-start; order: 7; padding: 0px 8px 0px 8px; width: min-content; }",
  ".framer-cs6CW.framer-v-1kenqkc .framer-tug0tr-container { height: 40px; order: 8; right: 16px; top: 8px; }",
  '.framer-cs6CW[data-border="true"]::after, .framer-cs6CW [data-border="true"]::after { content: ""; border-width: var(--border-top-width, 0) var(--border-right-width, 0) var(--border-bottom-width, 0) var(--border-left-width, 0); border-color: var(--border-color, none); border-style: var(--border-style, none); width: 100%; height: 100%; position: absolute; box-sizing: border-box; left: 0; top: 0; border-radius: inherit; corner-shape: inherit; pointer-events: none; }',
];
/**
 * This is a generated Framer component.
 * @framerIntrinsicHeight 64
 * @framerIntrinsicWidth 1200
 * @framerCanvasComponentVariantDetails {"propertyName":"variant","data":{"default":{"layout":["fixed","fixed"]},"tCDt2iF8Z":{"layout":["fixed","fixed"]},"zPJ3g9Bac":{"layout":["fixed","fixed"]},"YNJh_zUwK":{"layout":["fixed","fixed"]}}}
 * @framerImmutableVariables true
 * @framerDisplayContentsDiv false
 * @framerAutoSizeImages true
 * @framerComponentViewportWidth true
 * @framerColorSyntax true
 */ const FramerhuAklyris = withCSS(Component, css, "framer-cs6CW");
export default FramerhuAklyris;
FramerhuAklyris.displayName = "Header";
FramerhuAklyris.defaultProps = { height: 64, width: 1200 };
addPropertyControls(FramerhuAklyris, {
  variant: {
    options: ["KseaieyoG", "tCDt2iF8Z", "zPJ3g9Bac", "YNJh_zUwK"],
    optionTitles: ["Desktop", "Tablet", "Phone", "Variant 4"],
    title: "Variant",
    type: ControlType.Enum,
  },
});
addFonts(
  FramerhuAklyris,
  [
    {
      explicitInter: true,
      fonts: [
        {
          cssFamilyName: "DM Sans",
          source: "google",
          style: "normal",
          uiFamilyName: "DM Sans",
          url: "https://fonts.gstatic.com/s/dmsans/v17/rP2tp2ywxg089UriI5-g4vlH9VoD8CmcqZG40F9JadbnoEwAfJthS2f3ZGMZpg.woff2",
          weight: "600",
        },
      ],
    },
    ...MenuFonts,
    ...DownloadButtonFonts,
  ],
  { supportsExplicitInterCodegen: true }
);
FramerhuAklyris.loader = {
  load: (props, context) => {
    const locale = context.locale;
    return Promise.allSettled([forwardLoader(DownloadButton, {}, context)]);
  },
};
export const __FramerMetadata__ = {
  exports: {
    default: {
      type: "reactComponent",
      name: "FramerhuAklyris",
      slots: [],
      annotations: {
        framerColorSyntax: "true",
        framerCanvasComponentVariantDetails:
          '{"propertyName":"variant","data":{"default":{"layout":["fixed","fixed"]},"tCDt2iF8Z":{"layout":["fixed","fixed"]},"zPJ3g9Bac":{"layout":["fixed","fixed"]},"YNJh_zUwK":{"layout":["fixed","fixed"]}}}',
        framerIntrinsicWidth: "1200",
        framerAutoSizeImages: "true",
        framerImmutableVariables: "true",
        framerIntrinsicHeight: "64",
        framerContractVersion: "1",
        framerComponentViewportWidth: "true",
        framerDisplayContentsDiv: "false",
      },
    },
    Props: { type: "tsType", annotations: { framerContractVersion: "1" } },
    __FramerMetadata__: { type: "variable" },
  },
};
//# sourceMappingURL=./huAklyris.map
