// Generated by Framer (0951425)
import {
  addPropertyControls as e,
  ControlType as l,
  QueryEngine as t,
} from "framer";
import {
  DatabaseCollection as a,
  DatabaseDictionaryIndex as r,
} from "./NeoBePMHR-0.js";
import { getRichTextJsonResolver as i } from "./NeoBePMHR-1.js";
let o = {
    a_Uv7AzNk: { isNullable: !0, type: l.RichText },
    aWFYMJcy0: { isNullable: !0, type: l.RichText },
    BsY85ACO4: { isNullable: !0, type: l.String },
    cgjS3ceBS: { isNullable: !0, type: l.String },
    createdAt: { isNullable: !0, type: l.Date },
    dBbymHOHR: { isNullable: !0, type: l.RichText },
    Et2og6tjr: { isNullable: !0, type: l.RichText },
    I0HT_nwJ7: { isNullable: !0, type: l.RichText },
    id: { isNullable: !1, type: l.String },
    Inivpn_mb: { isNullable: !0, type: l.RichText },
    iunsfOpPD: { isNullable: !0, type: l.String },
    KL1iR4hbH: { isNullable: !0, type: l.String },
    nextItemId: { isNullable: !0, type: l.String },
    NoGKYos5o: { isNullable: !0, type: l.RichText },
    On8gChY7n: { isNullable: !0, type: l.ResponsiveImage },
    previousItemId: { isNullable: !0, type: l.String },
    qCkU5tRH4: { isNullable: !0, type: l.RichText },
    t9MSIGTrE: { isNullable: !0, type: l.RichText },
    u3QvKZaOu: { isNullable: !0, type: l.RichText },
    updatedAt: { isNullable: !0, type: l.Date },
    xyhMABppl: { isNullable: !0, type: l.RichText },
    y3QQHjJRj: { isNullable: !0, type: l.Boolean },
  },
  m = ["id"],
  c = { type: 1 },
  n = ["previousItemId"],
  u = ["nextItemId"],
  s = ["id", "cgjS3ceBS"],
  d = ["cgjS3ceBS", "id"],
  f = ["KL1iR4hbH"],
  p = { type: 0 },
  R = ["iunsfOpPD"],
  h = ["cgjS3ceBS"],
  y = ["On8gChY7n"],
  N = ["NoGKYos5o"],
  g = ["t9MSIGTrE"],
  x = ["I0HT_nwJ7"],
  S = ["qCkU5tRH4"],
  w = ["dBbymHOHR"],
  B = ["Inivpn_mb"],
  H = ["u3QvKZaOu"],
  M = ["Et2og6tjr"],
  b = ["aWFYMJcy0"],
  P = ["xyhMABppl"],
  I = ["a_Uv7AzNk"],
  L = ["BsY85ACO4"],
  U = ["y3QQHjJRj"],
  T = [],
  v = (e) => {
    let l = T[e];
    if (l) return l().then((e) => e.default);
  },
  V = {},
  j = i(V),
  k = new t(),
  O = {
    collectionByLocaleId: {
      default: new a({
        chunks: [
          new URL(
            "./NeoBePMHR-chunk-default-0.framercms",
            import.meta.url
          ).href.replace("/modules/", "/cms/"),
        ],
        id: "859d7363-f1c6-4d0a-ab88-cd00253cc080default",
        indexes: [
          new r({
            collation: c,
            collectionSchema: o,
            fieldNames: m,
            range: { from: 0, to: 361 },
            url: new URL(
              "./NeoBePMHR-indexes-default-0.framercms",
              import.meta.url
            ).href.replace("/modules/", "/cms/"),
          }),
          new r({
            collation: c,
            collectionSchema: o,
            fieldNames: n,
            range: { from: 361, to: 721 },
            url: new URL(
              "./NeoBePMHR-indexes-default-0.framercms",
              import.meta.url
            ).href.replace("/modules/", "/cms/"),
          }),
          new r({
            collation: c,
            collectionSchema: o,
            fieldNames: u,
            range: { from: 721, to: 1077 },
            url: new URL(
              "./NeoBePMHR-indexes-default-0.framercms",
              import.meta.url
            ).href.replace("/modules/", "/cms/"),
          }),
          new r({
            collation: c,
            collectionSchema: o,
            fieldNames: s,
            range: { from: 1077, to: 1719 },
            url: new URL(
              "./NeoBePMHR-indexes-default-0.framercms",
              import.meta.url
            ).href.replace("/modules/", "/cms/"),
          }),
          new r({
            collation: c,
            collectionSchema: o,
            fieldNames: d,
            range: { from: 1719, to: 2361 },
            url: new URL(
              "./NeoBePMHR-indexes-default-0.framercms",
              import.meta.url
            ).href.replace("/modules/", "/cms/"),
          }),
          new r({
            collation: p,
            collectionSchema: o,
            fieldNames: f,
            range: { from: 2361, to: 2816 },
            url: new URL(
              "./NeoBePMHR-indexes-default-0.framercms",
              import.meta.url
            ).href.replace("/modules/", "/cms/"),
          }),
          new r({
            collation: p,
            collectionSchema: o,
            fieldNames: R,
            range: { from: 2816, to: 4030 },
            url: new URL(
              "./NeoBePMHR-indexes-default-0.framercms",
              import.meta.url
            ).href.replace("/modules/", "/cms/"),
          }),
          new r({
            collation: p,
            collectionSchema: o,
            fieldNames: h,
            range: { from: 4030, to: 4470 },
            url: new URL(
              "./NeoBePMHR-indexes-default-0.framercms",
              import.meta.url
            ).href.replace("/modules/", "/cms/"),
          }),
          new r({
            collation: p,
            collectionSchema: o,
            fieldNames: y,
            range: { from: 4470, to: 8370 },
            url: new URL(
              "./NeoBePMHR-indexes-default-0.framercms",
              import.meta.url
            ).href.replace("/modules/", "/cms/"),
          }),
          new r({
            collation: p,
            collectionSchema: o,
            fieldNames: N,
            range: { from: 8370, to: 28549 },
            url: new URL(
              "./NeoBePMHR-indexes-default-0.framercms",
              import.meta.url
            ).href.replace("/modules/", "/cms/"),
          }),
          new r({
            collation: p,
            collectionSchema: o,
            fieldNames: g,
            range: { from: 28549, to: 32475 },
            url: new URL(
              "./NeoBePMHR-indexes-default-0.framercms",
              import.meta.url
            ).href.replace("/modules/", "/cms/"),
          }),
          new r({
            collation: p,
            collectionSchema: o,
            fieldNames: x,
            range: { from: 32475, to: 36449 },
            url: new URL(
              "./NeoBePMHR-indexes-default-0.framercms",
              import.meta.url
            ).href.replace("/modules/", "/cms/"),
          }),
          new r({
            collation: p,
            collectionSchema: o,
            fieldNames: S,
            range: { from: 36449, to: 39914 },
            url: new URL(
              "./NeoBePMHR-indexes-default-0.framercms",
              import.meta.url
            ).href.replace("/modules/", "/cms/"),
          }),
          new r({
            collation: p,
            collectionSchema: o,
            fieldNames: w,
            range: { from: 39914, to: 43271 },
            url: new URL(
              "./NeoBePMHR-indexes-default-0.framercms",
              import.meta.url
            ).href.replace("/modules/", "/cms/"),
          }),
          new r({
            collation: p,
            collectionSchema: o,
            fieldNames: B,
            range: { from: 43271, to: 45906 },
            url: new URL(
              "./NeoBePMHR-indexes-default-0.framercms",
              import.meta.url
            ).href.replace("/modules/", "/cms/"),
          }),
          new r({
            collation: p,
            collectionSchema: o,
            fieldNames: H,
            range: { from: 45906, to: 47225 },
            url: new URL(
              "./NeoBePMHR-indexes-default-0.framercms",
              import.meta.url
            ).href.replace("/modules/", "/cms/"),
          }),
          new r({
            collation: p,
            collectionSchema: o,
            fieldNames: M,
            range: { from: 47225, to: 47740 },
            url: new URL(
              "./NeoBePMHR-indexes-default-0.framercms",
              import.meta.url
            ).href.replace("/modules/", "/cms/"),
          }),
          new r({
            collation: p,
            collectionSchema: o,
            fieldNames: b,
            range: { from: 47740, to: 47926 },
            url: new URL(
              "./NeoBePMHR-indexes-default-0.framercms",
              import.meta.url
            ).href.replace("/modules/", "/cms/"),
          }),
          new r({
            collation: p,
            collectionSchema: o,
            fieldNames: P,
            range: { from: 47926, to: 48112 },
            url: new URL(
              "./NeoBePMHR-indexes-default-0.framercms",
              import.meta.url
            ).href.replace("/modules/", "/cms/"),
          }),
          new r({
            collation: p,
            collectionSchema: o,
            fieldNames: I,
            range: { from: 48112, to: 71784 },
            url: new URL(
              "./NeoBePMHR-indexes-default-0.framercms",
              import.meta.url
            ).href.replace("/modules/", "/cms/"),
          }),
          new r({
            collation: p,
            collectionSchema: o,
            fieldNames: L,
            range: { from: 71784, to: 77072 },
            url: new URL(
              "./NeoBePMHR-indexes-default-0.framercms",
              import.meta.url
            ).href.replace("/modules/", "/cms/"),
          }),
          new r({
            collation: p,
            collectionSchema: o,
            fieldNames: U,
            range: { from: 77072, to: 77272 },
            url: new URL(
              "./NeoBePMHR-indexes-default-0.framercms",
              import.meta.url
            ).href.replace("/modules/", "/cms/"),
          }),
        ],
        resolveRichText: j,
        resolveVectorSetItem: v,
        schema: o,
      }),
    },
    displayName: "People 2",
    id: "859d7363-f1c6-4d0a-ab88-cd00253cc080",
  };
export default O;
e(O, {
  KL1iR4hbH: { defaultValue: "", title: "Name", type: l.String },
  iunsfOpPD: { defaultValue: "", title: "Title", type: l.String },
  cgjS3ceBS: { preventLocalization: !1, title: "Slug", type: l.String },
  On8gChY7n: { title: "Photo", type: l.ResponsiveImage },
  NoGKYos5o: { defaultValue: "", title: "Bio", type: l.RichText },
  t9MSIGTrE: { defaultValue: "", title: "link-1", type: l.RichText },
  I0HT_nwJ7: { defaultValue: "", title: "link-2", type: l.RichText },
  qCkU5tRH4: { defaultValue: "", title: "link-3", type: l.RichText },
  dBbymHOHR: { defaultValue: "", title: "link-4", type: l.RichText },
  Inivpn_mb: { defaultValue: "", title: "link-5", type: l.RichText },
  u3QvKZaOu: { defaultValue: "", title: "link-6", type: l.RichText },
  Et2og6tjr: { defaultValue: "", title: "link-7", type: l.RichText },
  aWFYMJcy0: { defaultValue: "", title: "link-8", type: l.RichText },
  xyhMABppl: { defaultValue: "", title: "link-9", type: l.RichText },
  a_Uv7AzNk: { defaultValue: "", title: "Selected work", type: l.RichText },
  BsY85ACO4: { defaultValue: "", title: "Areas of Expertise", type: l.String },
  y3QQHjJRj: {
    defaultValue: !0,
    title: 'Visibility in "About Us" grid',
    type: l.Boolean,
  },
  createdAt: { title: "Created", type: l.Date },
  updatedAt: { title: "Updated", type: l.Date },
  previousItemId: {
    dataIdentifier: "local-module:collection/NeoBePMHR:default",
    title: "Previous",
    type: l.CollectionReference,
  },
  nextItemId: {
    dataIdentifier: "local-module:collection/NeoBePMHR:default",
    title: "Next",
    type: l.CollectionReference,
  },
});
export const enumToDisplayNameFunctions = {};
export const utils = {
  async getSlugByRecordId(e, l) {
    let [t] = await k.query(
      {
        from: { data: O, type: "Collection" },
        limit: { type: "LiteralValue", value: 1 },
        select: [{ name: "cgjS3ceBS", type: "Identifier" }],
        where: {
          left: { name: "id", type: "Identifier" },
          operator: "==",
          right: { type: "LiteralValue", value: e },
          type: "BinaryOperation",
        },
      },
      l
    );
    return t?.cgjS3ceBS;
  },
  async getRecordIdBySlug(e, l) {
    let [t] = await k.query(
      {
        from: { data: O, type: "Collection" },
        limit: { type: "LiteralValue", value: 1 },
        select: [{ name: "id", type: "Identifier" }],
        where: {
          left: { name: "cgjS3ceBS", type: "Identifier" },
          operator: "==",
          right: { type: "LiteralValue", value: e },
          type: "BinaryOperation",
        },
      },
      l
    );
    return t?.id;
  },
};
export const __FramerMetadata__ = {
  exports: {
    utils: { type: "variable", annotations: { framerContractVersion: "1" } },
    enumToDisplayNameFunctions: {
      type: "variable",
      annotations: { framerContractVersion: "1" },
    },
    default: {
      type: "data",
      name: "data",
      annotations: {
        framerAutoSizeImages: "true",
        framerRecordIdKey: "id",
        framerData: "true",
        framerContractVersion: "1",
        framerCollectionUtils: "1",
        framerCollectionId: "NeoBePMHR",
        framerEnumToDisplayNameUtils: "2",
        framerColorSyntax: "false",
        framerSlug: "cgjS3ceBS",
      },
    },
    __FramerMetadata__: { type: "variable" },
  },
};
