// Generated by Framer (375af7e)
export default function metadata(params, activeLocale) {
  return {
    description:
      "Ash is the first AI designed for mental health. Get support for stress, anxiety, relationships, or a bad day. Ash can help right now or build for long-term growth with a private, zero judgment space to speak freely.",
    favicon:
      "https://framerusercontent.com/assets/yu2Y2aEeuoC9xHd0VtWpziH4.png",
    robots: "max-image-preview:large",
    socialImage:
      "https://framerusercontent.com/assets/9AcZJyICevtVVL9vPJdPtQt7O44.png",
    title: "Ash - AI for Mental Health",
  };
}
export const metadataVersion = 1;
export const __FramerMetadata__ = {
  exports: {
    metadataVersion: {
      type: "variable",
      annotations: { framerContractVersion: "1" },
    },
    default: { type: "function", annotations: { framerContractVersion: "1" } },
    __FramerMetadata__: { type: "variable" },
  },
};
