// Generated by Framer (27dd866)
import siteMetadata from "#framer/local/siteMetadata/siteMetadata/siteMetadata.js";
export default function metadata(params, activeLocale) {
  return {
    breakpoints: [
      { hash: "1h2bakc", mediaQuery: "(min-width: 1200px)" },
      {
        hash: "14x34wb",
        mediaQuery: "(min-width: 810px) and (max-width: 1199.98px)",
      },
      { hash: "wi339a", mediaQuery: "(max-width: 809.98px)" },
    ],
    description: siteMetadata(params, activeLocale).description,
    elements: {},
    framerSearch: { index: true },
    robots: "max-image-preview:large",
    serializationId: "framer-9PdKv",
    title: "Resources - Ash",
    viewport: "width=device-width",
  };
}
export const metadataVersion = 1;
export const __FramerMetadata__ = {
  exports: {
    default: { type: "function", annotations: { framerContractVersion: "1" } },
    metadataVersion: {
      type: "variable",
      annotations: { framerContractVersion: "1" },
    },
    __FramerMetadata__: { type: "variable" },
  },
};
