// Generated by Framer (b6d5dad)
import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import {
  addFonts,
  addPropertyControls,
  ControlType,
  cx,
  useActiveVariantCallback,
  useComponentViewport,
  useLocaleInfo,
  useVariantState,
  withCSS,
} from "framer";
import { LayoutGroup, motion, MotionConfigContext } from "framer-motion";
import * as React from "react";
import { useRef } from "react";
const cycleOrder = ["dKQ0QYYHx", "B1LH91gFj", "tv3nU8XHS"];
const serializationHash = "framer-APTnR";
const variantClassNames = {
  B1LH91gFj: "framer-v-1x9cedb",
  dKQ0QYYHx: "framer-v-1pxo5d7",
  tv3nU8XHS: "framer-v-1swctxz",
};
function addPropertyOverrides(overrides, ...variants) {
  const nextOverrides = {};
  variants?.forEach(
    (variant) => variant && Object.assign(nextOverrides, overrides[variant])
  );
  return nextOverrides;
}
const transition1 = {
  damping: 40,
  delay: 0,
  mass: 1,
  stiffness: 250,
  type: "spring",
};
const Transition = ({ value, children }) => {
  const config = React.useContext(MotionConfigContext);
  const transition = value ?? config.transition;
  const contextValue = React.useMemo(
    () => ({ ...config, transition }),
    [JSON.stringify(transition)]
  );
  return /*#__PURE__*/ _jsx(MotionConfigContext.Provider, {
    value: contextValue,
    children: children,
  });
};
const Variants = motion.create(React.Fragment);
const humanReadableVariantMap = {
  Hover: "tv3nU8XHS",
  Minus: "B1LH91gFj",
  Plus: "dKQ0QYYHx",
};
const getProps = ({ height, id, width, ...props }) => {
  return {
    ...props,
    variant:
      humanReadableVariantMap[props.variant] ?? props.variant ?? "dKQ0QYYHx",
  };
};
const createLayoutDependency = (props, variants) => {
  if (props.layoutDependency)
    return variants.join("-") + props.layoutDependency;
  return variants.join("-");
};
const Component = /*#__PURE__*/ React.forwardRef(function (props, ref) {
  const fallbackRef = useRef(null);
  const refBinding = ref ?? fallbackRef;
  const defaultLayoutId = React.useId();
  const { activeLocale, setLocale } = useLocaleInfo();
  const componentViewport = useComponentViewport();
  const { style, className, layoutId, variant, ...restProps } = getProps(props);
  const {
    baseVariant,
    classNames,
    clearLoadingGesture,
    gestureHandlers,
    gestureVariant,
    isLoading,
    setGestureState,
    setVariant,
    variants,
  } = useVariantState({
    cycleOrder,
    defaultVariant: "dKQ0QYYHx",
    ref: refBinding,
    variant,
    variantClassNames,
  });
  const layoutDependency = createLayoutDependency(props, variants);
  const { activeVariantCallback, delay } =
    useActiveVariantCallback(baseVariant);
  const onMouseEnter165myoe = activeVariantCallback(async (...args) => {
    setGestureState({ isHovered: true });
    setVariant("tv3nU8XHS");
  });
  const onMouseLeave76lbgy = activeVariantCallback(async (...args) => {
    setGestureState({ isHovered: false });
    setVariant("dKQ0QYYHx");
  });
  const sharedStyleClassNames = [];
  const scopingClassNames = cx(serializationHash, ...sharedStyleClassNames);
  return /*#__PURE__*/ _jsx(LayoutGroup, {
    id: layoutId ?? defaultLayoutId,
    children: /*#__PURE__*/ _jsx(Variants, {
      animate: variants,
      initial: false,
      children: /*#__PURE__*/ _jsx(Transition, {
        value: transition1,
        children: /*#__PURE__*/ _jsxs(motion.div, {
          ...restProps,
          ...gestureHandlers,
          className: cx(
            scopingClassNames,
            "framer-1pxo5d7",
            className,
            classNames
          ),
          "data-framer-name": "Plus",
          "data-highlight": true,
          layoutDependency: layoutDependency,
          layoutId: "dKQ0QYYHx",
          onMouseEnter: onMouseEnter165myoe,
          ref: refBinding,
          style: {
            backgroundColor:
              "var(--token-46c57772-6ea6-44fd-970d-ca4fb7a65057, rgb(229, 216, 202))",
            borderBottomLeftRadius: 80,
            borderBottomRightRadius: 80,
            borderTopLeftRadius: 80,
            borderTopRightRadius: 80,
            ...style,
          },
          variants: {
            B1LH91gFj: {
              backgroundColor:
                "var(--token-6c0aaddc-46bb-4a8c-a780-8357980b9d48, rgb(241, 230, 219))",
            },
            tv3nU8XHS: {
              backgroundColor:
                "var(--token-6c0aaddc-46bb-4a8c-a780-8357980b9d48, rgb(241, 230, 219))",
            },
          },
          ...addPropertyOverrides(
            {
              B1LH91gFj: {
                "data-framer-name": "Minus",
                onMouseLeave: onMouseLeave76lbgy,
              },
              tv3nU8XHS: {
                "data-framer-name": "Hover",
                onMouseLeave: onMouseLeave76lbgy,
              },
            },
            baseVariant,
            gestureVariant
          ),
          children: [
            /*#__PURE__*/ _jsx(motion.div, {
              className: "framer-1tpon8g",
              layoutDependency: layoutDependency,
              layoutId: "AS1k7gqub",
              style: {
                backgroundColor:
                  "var(--token-0ecaa262-9aac-4113-a5a5-5bfcb0d17214, rgb(53, 48, 43))",
                borderBottomLeftRadius: 102,
                borderBottomRightRadius: 102,
                borderTopLeftRadius: 102,
                borderTopRightRadius: 102,
                rotate: 0,
              },
              variants: {
                B1LH91gFj: { rotate: -180 },
                tv3nU8XHS: { rotate: 0 },
              },
            }),
            /*#__PURE__*/ _jsx(motion.div, {
              className: "framer-1pxq071",
              layoutDependency: layoutDependency,
              layoutId: "yr1lQQc6K",
              style: {
                backgroundColor:
                  "var(--token-0ecaa262-9aac-4113-a5a5-5bfcb0d17214, rgb(53, 48, 43))",
                borderBottomLeftRadius: 102,
                borderBottomRightRadius: 102,
                borderTopLeftRadius: 102,
                borderTopRightRadius: 102,
                rotate: 90,
              },
              variants: { B1LH91gFj: { rotate: -180 } },
            }),
          ],
        }),
      }),
    }),
  });
});
const css = [
  "@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }",
  ".framer-APTnR.framer-ncpsx3, .framer-APTnR .framer-ncpsx3 { display: block; }",
  ".framer-APTnR.framer-1pxo5d7 { align-content: center; align-items: center; display: flex; flex-direction: row; flex-wrap: nowrap; gap: 10px; height: 32px; justify-content: flex-start; overflow: visible; padding: 0px; position: relative; width: 32px; }",
  ".framer-APTnR .framer-1tpon8g, .framer-APTnR .framer-1pxq071 { flex: none; height: 2px; left: calc(50.00000000000002% - 14px / 2); overflow: hidden; position: absolute; top: calc(50.00000000000002% - 2px / 2); width: 14px; will-change: var(--framer-will-change-override, transform); z-index: 1; }",
  ".framer-APTnR.framer-v-1x9cedb.framer-1pxo5d7, .framer-APTnR.framer-v-1swctxz.framer-1pxo5d7 { aspect-ratio: 1 / 1; height: var(--framer-aspect-ratio-supported, 32px); }",
  ".framer-APTnR.framer-v-1swctxz .framer-1tpon8g, .framer-APTnR.framer-v-1swctxz .framer-1pxq071 { left: calc(50.00000000000002% - 16px / 2); width: 16px; }",
];
/**
 * This is a generated Framer component.
 * @framerIntrinsicHeight 32
 * @framerIntrinsicWidth 32
 * @framerCanvasComponentVariantDetails {"propertyName":"variant","data":{"default":{"layout":["fixed","fixed"]},"B1LH91gFj":{"layout":["fixed","fixed"]},"tv3nU8XHS":{"layout":["fixed","fixed"]}}}
 * @framerImmutableVariables true
 * @framerDisplayContentsDiv false
 * @framerAutoSizeImages true
 * @framerComponentViewportWidth true
 * @framerColorSyntax true
 */ const FrameryczviJyPO = withCSS(Component, css, "framer-APTnR");
export default FrameryczviJyPO;
FrameryczviJyPO.displayName = "Plus Icon";
FrameryczviJyPO.defaultProps = { height: 32, width: 32 };
addPropertyControls(FrameryczviJyPO, {
  variant: {
    options: ["dKQ0QYYHx", "B1LH91gFj", "tv3nU8XHS"],
    optionTitles: ["Plus", "Minus", "Hover"],
    title: "Variant",
    type: ControlType.Enum,
  },
});
addFonts(FrameryczviJyPO, [{ explicitInter: true, fonts: [] }], {
  supportsExplicitInterCodegen: true,
});
export const __FramerMetadata__ = {
  exports: {
    Props: { type: "tsType", annotations: { framerContractVersion: "1" } },
    default: {
      type: "reactComponent",
      name: "FrameryczviJyPO",
      slots: [],
      annotations: {
        framerAutoSizeImages: "true",
        framerIntrinsicWidth: "32",
        framerDisplayContentsDiv: "false",
        framerIntrinsicHeight: "32",
        framerCanvasComponentVariantDetails:
          '{"propertyName":"variant","data":{"default":{"layout":["fixed","fixed"]},"B1LH91gFj":{"layout":["fixed","fixed"]},"tv3nU8XHS":{"layout":["fixed","fixed"]}}}',
        framerImmutableVariables: "true",
        framerColorSyntax: "true",
        framerComponentViewportWidth: "true",
        framerContractVersion: "1",
      },
    },
    __FramerMetadata__: { type: "variable" },
  },
};
//# sourceMappingURL=./yczviJyPO.map
