// Generated by Framer (fe01371)
import {
  addPropertyControls as e,
  ControlType as l,
  QueryEngine as t,
} from "framer";
import {
  DatabaseCollection as a,
  DatabaseDictionaryIndex as r,
} from "./mWamWlFJs-0.js";
import { getRichTextJsonResolver as m } from "./mWamWlFJs-1.js";
let i = {
    createdAt: { isNullable: !0, type: l.Date },
    dH8JIZUv6: { isNullable: !0, type: l.Date },
    id: { isNullable: !1, type: l.String },
    JDSQr8aGf: {
      definition: { isNullable: !0, type: l.String },
      isNullable: !0,
      type: l.Array,
    },
    jZKiLqTdY: {
      definition: { isNullable: !0, type: l.String },
      isNullable: !0,
      type: l.Array,
    },
    L3nNRMQpR: { isNullable: !0, type: l.String },
    lV10udJUp: { isNullable: !0, type: l.String },
    nextItemId: { isNullable: !0, type: l.String },
    nfcmqaIA9: { isNullable: !0, type: l.RichText },
    O3nCZSQxg: {
      definition: { isNullable: !0, type: l.String },
      isNullable: !0,
      type: l.Array,
    },
    oVu836PGu: { isNullable: !0, type: l.Link },
    P9rN1fT95: { isNullable: !0, type: l.RichText },
    previousItemId: { isNullable: !0, type: l.String },
    ROM0Efl2y: { isNullable: !0, type: l.String },
    U7t12GuKW: { isNullable: !0, type: l.RichText },
    updatedAt: { isNullable: !0, type: l.Date },
    URsQ9QndF: { isNullable: !0, type: l.RichText },
    voVr60d5X: { isNullable: !0, type: l.ResponsiveImage },
    yFKSzw9P3: { isNullable: !0, type: l.Enum },
  },
  o = ["id"],
  n = { type: 1 },
  c = ["previousItemId"],
  s = ["nextItemId"],
  u = ["id", "lV10udJUp"],
  d = ["lV10udJUp", "id"],
  f = ["L3nNRMQpR"],
  p = { type: 0 },
  y = ["lV10udJUp"],
  h = ["ROM0Efl2y"],
  R = ["dH8JIZUv6"],
  w = ["URsQ9QndF"],
  N = ["U7t12GuKW"],
  S = ["JDSQr8aGf"],
  g = ["oVu836PGu"],
  W = ["voVr60d5X"],
  x = ["P9rN1fT95"],
  J = ["nfcmqaIA9"],
  F = ["yFKSzw9P3"],
  U = ["O3nCZSQxg"],
  L = ["jZKiLqTdY"],
  I = [],
  b = (e) => {
    let l = I[e];
    if (l) return l().then((e) => e.default);
  },
  V = {},
  v = m(V),
  T = new t(),
  P = {
    collectionByLocaleId: {
      default: new a({
        chunks: [
          new URL(
            "./mWamWlFJs-chunk-default-0.framercms",
            import.meta.url
          ).href.replace("/modules/", "/cms/"),
        ],
        id: "68d44e52-5d05-4a21-a570-091a6dccbd08default",
        indexes: [
          new r({
            collation: n,
            collectionSchema: i,
            fieldNames: o,
            range: { from: 0, to: 1009 },
            url: new URL(
              "./mWamWlFJs-indexes-default-0.framercms",
              import.meta.url
            ).href.replace("/modules/", "/cms/"),
          }),
          new r({
            collation: n,
            collectionSchema: i,
            fieldNames: c,
            range: { from: 1009, to: 2017 },
            url: new URL(
              "./mWamWlFJs-indexes-default-0.framercms",
              import.meta.url
            ).href.replace("/modules/", "/cms/"),
          }),
          new r({
            collation: n,
            collectionSchema: i,
            fieldNames: s,
            range: { from: 2017, to: 3021 },
            url: new URL(
              "./mWamWlFJs-indexes-default-0.framercms",
              import.meta.url
            ).href.replace("/modules/", "/cms/"),
          }),
          new r({
            collation: n,
            collectionSchema: i,
            fieldNames: u,
            range: { from: 3021, to: 5684 },
            url: new URL(
              "./mWamWlFJs-indexes-default-0.framercms",
              import.meta.url
            ).href.replace("/modules/", "/cms/"),
          }),
          new r({
            collation: n,
            collectionSchema: i,
            fieldNames: d,
            range: { from: 5684, to: 8347 },
            url: new URL(
              "./mWamWlFJs-indexes-default-0.framercms",
              import.meta.url
            ).href.replace("/modules/", "/cms/"),
          }),
          new r({
            collation: p,
            collectionSchema: i,
            fieldNames: f,
            range: { from: 8347, to: 11821 },
            url: new URL(
              "./mWamWlFJs-indexes-default-0.framercms",
              import.meta.url
            ).href.replace("/modules/", "/cms/"),
          }),
          new r({
            collation: p,
            collectionSchema: i,
            fieldNames: y,
            range: { from: 11821, to: 13904 },
            url: new URL(
              "./mWamWlFJs-indexes-default-0.framercms",
              import.meta.url
            ).href.replace("/modules/", "/cms/"),
          }),
          new r({
            collation: p,
            collectionSchema: i,
            fieldNames: h,
            range: { from: 13904, to: 15187 },
            url: new URL(
              "./mWamWlFJs-indexes-default-0.framercms",
              import.meta.url
            ).href.replace("/modules/", "/cms/"),
          }),
          new r({
            collation: p,
            collectionSchema: i,
            fieldNames: R,
            range: { from: 15187, to: 15974 },
            url: new URL(
              "./mWamWlFJs-indexes-default-0.framercms",
              import.meta.url
            ).href.replace("/modules/", "/cms/"),
          }),
          new r({
            collation: p,
            collectionSchema: i,
            fieldNames: w,
            range: { from: 15974, to: 28064 },
            url: new URL(
              "./mWamWlFJs-indexes-default-0.framercms",
              import.meta.url
            ).href.replace("/modules/", "/cms/"),
          }),
          new r({
            collation: p,
            collectionSchema: i,
            fieldNames: N,
            range: { from: 28064, to: 65238 },
            url: new URL(
              "./mWamWlFJs-indexes-default-0.framercms",
              import.meta.url
            ).href.replace("/modules/", "/cms/"),
          }),
          new r({
            collation: p,
            collectionSchema: i,
            fieldNames: S,
            range: { from: 65238, to: 65737 },
            url: new URL(
              "./mWamWlFJs-indexes-default-0.framercms",
              import.meta.url
            ).href.replace("/modules/", "/cms/"),
          }),
          new r({
            collation: p,
            collectionSchema: i,
            fieldNames: g,
            range: { from: 65737, to: 69417 },
            url: new URL(
              "./mWamWlFJs-indexes-default-0.framercms",
              import.meta.url
            ).href.replace("/modules/", "/cms/"),
          }),
          new r({
            collation: p,
            collectionSchema: i,
            fieldNames: W,
            range: { from: 69417, to: 93706 },
            url: new URL(
              "./mWamWlFJs-indexes-default-0.framercms",
              import.meta.url
            ).href.replace("/modules/", "/cms/"),
          }),
          new r({
            collation: p,
            collectionSchema: i,
            fieldNames: x,
            range: { from: 93706, to: 103588 },
            url: new URL(
              "./mWamWlFJs-indexes-default-0.framercms",
              import.meta.url
            ).href.replace("/modules/", "/cms/"),
          }),
          new r({
            collation: p,
            collectionSchema: i,
            fieldNames: J,
            range: { from: 103588, to: 104071 },
            url: new URL(
              "./mWamWlFJs-indexes-default-0.framercms",
              import.meta.url
            ).href.replace("/modules/", "/cms/"),
          }),
          new r({
            collation: p,
            collectionSchema: i,
            fieldNames: F,
            range: { from: 104071, to: 105087 },
            url: new URL(
              "./mWamWlFJs-indexes-default-0.framercms",
              import.meta.url
            ).href.replace("/modules/", "/cms/"),
          }),
          new r({
            collation: p,
            collectionSchema: i,
            fieldNames: U,
            range: { from: 105087, to: 105760 },
            url: new URL(
              "./mWamWlFJs-indexes-default-0.framercms",
              import.meta.url
            ).href.replace("/modules/", "/cms/"),
          }),
          new r({
            collation: p,
            collectionSchema: i,
            fieldNames: L,
            range: { from: 105760, to: 107301 },
            url: new URL(
              "./mWamWlFJs-indexes-default-0.framercms",
              import.meta.url
            ).href.replace("/modules/", "/cms/"),
          }),
        ],
        resolveRichText: v,
        resolveVectorSetItem: b,
        schema: i,
      }),
    },
    displayName: "news",
    id: "68d44e52-5d05-4a21-a570-091a6dccbd08",
  };
export default P;
e(P, {
  L3nNRMQpR: { defaultValue: "", title: "Title", type: l.String },
  lV10udJUp: { preventLocalization: !1, title: "Slug", type: l.String },
  ROM0Efl2y: { defaultValue: "", title: "Source", type: l.String },
  dH8JIZUv6: { title: "Date", type: l.Date },
  URsQ9QndF: { defaultValue: "", title: "The gist", type: l.RichText },
  U7t12GuKW: { defaultValue: "", title: "The details", type: l.RichText },
  JDSQr8aGf: {
    dataIdentifier: "local-module:collection/NeoBePMHR:default",
    title: "Featured",
    type: l.MultiCollectionReference,
  },
  oVu836PGu: { title: "Link", type: l.Link },
  voVr60d5X: {
    __defaultAssetReference:
      "data:framer/asset-reference,YRaxOkbEXSnvPtG4zAtKYP70.png?originalFilename=Ready.png&preferredSize=auto",
    title: "Image",
    type: l.ResponsiveImage,
  },
  P9rN1fT95: { defaultValue: "", title: "Content", type: l.RichText },
  nfcmqaIA9: { defaultValue: "", title: "Footnote", type: l.RichText },
  yFKSzw9P3: {
    defaultValue: "GbS3mxlv4",
    options: ["GbS3mxlv4", "y8FBrGElu", "Ay3SEpKJD", "LDIjQmYvV"],
    optionTitles: ["Blog", "News", "Research", ""],
    title: "Page",
    type: l.Enum,
  },
  O3nCZSQxg: {
    dataIdentifier: "local-module:collection/exj3nkrR7:default",
    title: "Related research",
    type: l.MultiCollectionReference,
  },
  jZKiLqTdY: {
    dataIdentifier: "local-module:collection/xIMP0tPj6:default",
    title: "Related posts",
    type: l.MultiCollectionReference,
  },
  createdAt: { title: "Created", type: l.Date },
  updatedAt: { title: "Updated", type: l.Date },
  previousItemId: {
    dataIdentifier: "local-module:collection/mWamWlFJs:default",
    title: "Previous",
    type: l.CollectionReference,
  },
  nextItemId: {
    dataIdentifier: "local-module:collection/mWamWlFJs:default",
    title: "Next",
    type: l.CollectionReference,
  },
});
export const yFKSzw9P3ToDisplayName = (e, l) => {
  switch ((l?.fallback, e)) {
    case "GbS3mxlv4":
      return "Blog";
    case "y8FBrGElu":
      return "News";
    case "Ay3SEpKJD":
      return "Research";
    default:
      return "";
  }
};
export const enumToDisplayNameFunctions = { yFKSzw9P3: yFKSzw9P3ToDisplayName };
export const utils = {
  async getSlugByRecordId(e, l) {
    let [t] = await T.query(
      {
        from: { data: P, type: "Collection" },
        limit: { type: "LiteralValue", value: 1 },
        select: [{ name: "lV10udJUp", type: "Identifier" }],
        where: {
          left: { name: "id", type: "Identifier" },
          operator: "==",
          right: { type: "LiteralValue", value: e },
          type: "BinaryOperation",
        },
      },
      l
    );
    return t?.lV10udJUp;
  },
  async getRecordIdBySlug(e, l) {
    let [t] = await T.query(
      {
        from: { data: P, type: "Collection" },
        limit: { type: "LiteralValue", value: 1 },
        select: [{ name: "id", type: "Identifier" }],
        where: {
          left: { name: "lV10udJUp", type: "Identifier" },
          operator: "==",
          right: { type: "LiteralValue", value: e },
          type: "BinaryOperation",
        },
      },
      l
    );
    return t?.id;
  },
};
export const __FramerMetadata__ = {
  exports: {
    utils: { type: "variable", annotations: { framerContractVersion: "1" } },
    yFKSzw9P3ToDisplayName: {
      type: "variable",
      annotations: { framerContractVersion: "1" },
    },
    enumToDisplayNameFunctions: {
      type: "variable",
      annotations: { framerContractVersion: "1" },
    },
    default: {
      type: "data",
      name: "data",
      annotations: {
        framerEnumToDisplayNameUtils: "2",
        framerSlug: "lV10udJUp",
        framerContractVersion: "1",
        framerAutoSizeImages: "true",
        framerRecordIdKey: "id",
        framerCollectionId: "mWamWlFJs",
        framerColorSyntax: "false",
        framerData: "true",
        framerCollectionUtils: "1",
      },
    },
    __FramerMetadata__: { type: "variable" },
  },
};
