// Generated by Framer (7e6a191)
import siteMetadata from "#framer/local/siteMetadata/siteMetadata/siteMetadata.js";
export default function metadata(params, activeLocale) {
  return {
    breakpoints: [
      { hash: "72rtr7", mediaQuery: "(min-width: 1200px)" },
      {
        hash: "p6drtb",
        mediaQuery: "(min-width: 810px) and (max-width: 1199.98px)",
      },
      { hash: "1jsxl1l", mediaQuery: "(max-width: 809.98px)" },
    ],
    description: siteMetadata(params, activeLocale).description,
    elements: {},
    robots: "max-image-preview:large",
    serializationId: "framer-i4b3s",
    title: siteMetadata(params, activeLocale).title || "Home",
    viewport: "width=device-width",
  };
}
export const metadataVersion = 1;
export const __FramerMetadata__ = {
  exports: {
    default: { type: "function", annotations: { framerContractVersion: "1" } },
    metadataVersion: {
      type: "variable",
      annotations: { framerContractVersion: "1" },
    },
    __FramerMetadata__: { type: "variable" },
  },
};
