// Generated by Framer (b6d5dad)
import { fontStore } from "framer";
fontStore.loadFonts(["CUSTOM;PP Fragment Glare Medium"]);
export const fonts = [
  {
    explicitInter: true,
    fonts: [
      {
        family: "PP Fragment Glare Medium",
        source: "custom",
        url: "https://framerusercontent.com/assets/nfABjCxm0nwdUOZ8OsNfdPrZTJg.woff2",
      },
    ],
  },
];
export const css = [
  '.framer-xWajt .framer-styles-preset-t4gi0o:not(.rich-text-wrapper), .framer-xWajt .framer-styles-preset-t4gi0o.rich-text-wrapper h2 { --framer-font-family: "PP Fragment Glare Medium", "PP Fragment Glare Medium Placeholder", sans-serif; --framer-font-open-type-features: normal; --framer-font-size: 40px; --framer-font-style: normal; --framer-font-variation-axes: normal; --framer-font-weight: 400; --framer-letter-spacing: -0.02em; --framer-line-height: 1.2em; --framer-paragraph-spacing: 40px; --framer-text-alignment: start; --framer-text-color: var(--token-0ecaa262-9aac-4113-a5a5-5bfcb0d17214, #35302b); --framer-text-decoration: none; --framer-text-stroke-color: initial; --framer-text-stroke-width: initial; --framer-text-transform: none; }',
  '@media (max-width: 1199px) and (min-width: 810px) { .framer-xWajt .framer-styles-preset-t4gi0o:not(.rich-text-wrapper), .framer-xWajt .framer-styles-preset-t4gi0o.rich-text-wrapper h2 { --framer-font-family: "PP Fragment Glare Medium", "PP Fragment Glare Medium Placeholder", sans-serif; --framer-font-open-type-features: normal; --framer-font-size: 32px; --framer-font-style: normal; --framer-font-variation-axes: normal; --framer-font-weight: 400; --framer-letter-spacing: -0.02em; --framer-line-height: 1.2em; --framer-paragraph-spacing: 40px; --framer-text-alignment: start; --framer-text-color: var(--token-0ecaa262-9aac-4113-a5a5-5bfcb0d17214, #35302b); --framer-text-decoration: none; --framer-text-stroke-color: initial; --framer-text-stroke-width: initial; --framer-text-transform: none; } }',
  '@media (max-width: 809px) and (min-width: 0px) { .framer-xWajt .framer-styles-preset-t4gi0o:not(.rich-text-wrapper), .framer-xWajt .framer-styles-preset-t4gi0o.rich-text-wrapper h2 { --framer-font-family: "PP Fragment Glare Medium", "PP Fragment Glare Medium Placeholder", sans-serif; --framer-font-open-type-features: normal; --framer-font-size: 26px; --framer-font-style: normal; --framer-font-variation-axes: normal; --framer-font-weight: 400; --framer-letter-spacing: -0.02em; --framer-line-height: 1.2em; --framer-paragraph-spacing: 40px; --framer-text-alignment: start; --framer-text-color: var(--token-0ecaa262-9aac-4113-a5a5-5bfcb0d17214, #35302b); --framer-text-decoration: none; --framer-text-stroke-color: initial; --framer-text-stroke-width: initial; --framer-text-transform: none; } }',
];
export const className = "framer-xWajt";
export const __FramerMetadata__ = {
  exports: {
    fonts: { type: "variable", annotations: { framerContractVersion: "1" } },
    className: {
      type: "variable",
      annotations: { framerContractVersion: "1" },
    },
    css: { type: "variable", annotations: { framerContractVersion: "1" } },
    __FramerMetadata__: { type: "variable" },
  },
};
